const assert = require("node:assert/strict");
const { EventEmitter } = require("node:events");
const { mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } = require("node:fs");
const { tmpdir } = require("node:os");
const path = require("node:path");
const { PassThrough } = require("node:stream");
const test = require("node:test");
const {
    createHash,
    generateKeyPairSync,
    sign,
} = require("node:crypto");
const { buildSync } = require("esbuild");

function loadModule() {
    const output = buildSync({
        entryPoints: [path.join(__dirname, "../src/runtime/installer.ts")],
        bundle: true,
        format: "cjs",
        platform: "node",
        target: "node16",
        write: false,
    }).outputFiles[0].text;
    const compiled = { exports: {} };
    new Function("require", "module", "exports", output)(require, compiled, compiled.exports);
    return compiled.exports;
}

function canonical(value) {
    const sort = (item) => Array.isArray(item) ? item.map(sort) : item && typeof item === "object"
        ? Object.fromEntries(Object.keys(item).sort().map((key) => [key, sort(item[key])])) : item;
    return Buffer.from(`${JSON.stringify(sort(value))}\n`, "utf8");
}

function digest(value) {
    return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

function base64url(value) {
    return value.toString("base64").replace(/=/g, "").replace(/\+/g, "-").replace(/\//g, "_");
}

// Generated by offeragent_harness.runtime.release_privileges from the canonical
// production process catalog. The hard-coded fingerprint is a cross-language
// canonicalization golden, not a value recomputed by this test.
const PRIVILEGE_ENVELOPE = {
    allowedNetworkCategories: ["model", "signed_update"],
    environmentProfiles: [{ allowedNames: [], allowedSecretNames: [], profileId: "minimal" }],
    executableProfiles: [
        {
            allowShellMetacharacters: false,
            allowedCwdRootIds: ["process-scratch"],
            allowedStdinModes: ["fixed_payload"],
            appContainerFilesystem: [{ access: "read_write", relativePath: "working", rootId: "process-scratch" }],
            environmentProfileIds: ["minimal"],
            executableId: "hook-continue",
            fixedArguments: ["hook-continue"],
            maximumVariableArguments: 0,
            minimumVariableArguments: 0,
            privilegeFingerprint: "sha256:92b5c3767c2beb843bdc9b8ea2d47c58d94c92df218dc5ce348300adc27e5261",
            relativePath: "offeragent-process-host.exe",
            trust: "signed_release",
            variableArgumentPattern: "^[^\\x00-\\x1f\\x7f&|<>^;`]{0,4096}$",
        },
        {
            allowShellMetacharacters: false,
            allowedCwdRootIds: ["process-scratch"],
            allowedStdinModes: ["closed"],
            appContainerFilesystem: [{ access: "read_write", relativePath: "working", rootId: "process-scratch" }],
            environmentProfileIds: ["minimal"],
            executableId: "shell-runtime-info",
            fixedArguments: ["shell-runtime-info"],
            maximumVariableArguments: 0,
            minimumVariableArguments: 0,
            privilegeFingerprint: "sha256:4f9a95da8df898f4eec17cb47719f84768e93c4ea9546e7b1bc7868d77305566",
            relativePath: "offeragent-process-host.exe",
            trust: "signed_release",
            variableArgumentPattern: "^[^\\x00-\\x1f\\x7f&|<>^;`]{0,4096}$",
        },
    ],
    fingerprint: "sha256:08ee5aeccb5e3a19f6d56710b9e7ff1a707d9f0ff977d41642ace38eae2c500a",
    localProcessNetwork: false,
    processCatalogSha256: "sha256:fdbc012b01fe10258e01d42967617bd8ecb42f6b101ca65f9affd5c9425ebd96",
    profilePrivileges: [
        {
            allowNetwork: false,
            allowedCwdRootIds: ["process-scratch"],
            allowedPlainEnvironmentNames: [],
            allowedSecretEnvironmentNames: [],
            environmentProfileIds: ["minimal"],
            executableId: "hook-continue",
            fixedArguments: ["hook-continue"],
            kind: "hook",
            maximumVariableArguments: 0,
            minimumVariableArguments: 0,
            privilegeFingerprint: "sha256:d9cc66d30c017c7fe07c3dea82399dade3ce43b5d742b53ee244c0ec8f96a75e",
            profileId: "hook-continue",
            risk: "execute",
            sideEffectClass: "execute",
            variableArgumentPattern: "^[^\\x00-\\x1f\\x7f&|<>^;`]{0,4096}$",
        },
        {
            allowNetwork: false,
            allowedCwdRootIds: ["process-scratch"],
            allowedPlainEnvironmentNames: [],
            allowedSecretEnvironmentNames: [],
            environmentProfileIds: ["minimal"],
            executableId: "shell-runtime-info",
            fixedArguments: ["shell-runtime-info"],
            kind: "shell",
            maximumVariableArguments: 0,
            minimumVariableArguments: 0,
            privilegeFingerprint: "sha256:f180ddda8339392e66a2dbc0077064362eac2b030158142aa343221d68472cf5",
            profileId: "runtime-info",
            risk: "execute",
            sideEffectClass: "execute",
            variableArgumentPattern: "^[^\\x00-\\x1f\\x7f&|<>^;`]{0,4096}$",
        },
    ],
    rootCapabilities: [
        { access: "cwd", relativePath: ".", rootId: "process-scratch" },
        { access: "read_write", relativePath: "working", rootId: "process-scratch" },
    ],
    schemaVersion: 1,
};

function pe(machine = 0x8664) {
    const value = Buffer.alloc(88);
    value.write("MZ", 0, "ascii");
    value.writeUInt32LE(64, 60);
    value.write("PE\0\0", 64, "binary");
    value.writeUInt16LE(machine, 68);
    return value;
}

function peX64() {
    return pe(0x8664);
}

function makeBundle({ manifestArchitecture = "x64", bootstrapMachine = 0x8664 } = {}) {
    const plugin = mkdtempSync(path.join(tmpdir(), "offeragent-installer-"));
    const previousLocalAppData = process.env.LOCALAPPDATA;
    process.env.LOCALAPPDATA = path.join(plugin, "localappdata");
    mkdirSync(process.env.LOCALAPPDATA, { recursive: true });
    const root = path.join(plugin, "runtime");
    const platformRoot = path.join(root, "windows-x64");
    mkdirSync(platformRoot, { recursive: true });
    const helper = pe(bootstrapMachine);
    const files = [
        ["LICENSES/a", "license", false],
        ["offeragent-host.exe", "executable", true],
        ["offeragent-process-host.exe", "executable", true],
        ["offeragent-self-test.exe", "executable", true],
        ["offeragent-worker.exe", "executable", true],
        ["process-catalog.v1.json", "asset", false],
        ["provenance/a", "provenance", false],
        ["sbom/a", "sbom", false],
        ["web/index.html", "web", false],
    ].map(([filePath, kind, authenticode]) => ({
        path: filePath,
        byteLength: filePath === "process-catalog.v1.json" ? 1876 : 1,
        sha256: filePath === "process-catalog.v1.json"
            ? PRIVILEGE_ENVELOPE.processCatalogSha256 : digest(Buffer.from(filePath)),
        kind,
        authenticode,
    }));
    const contentDigest = digest(Buffer.from(JSON.stringify(
        files.map(({ path: filePath, byteLength, sha256 }) => ({ byteLength, path: filePath, sha256 })),
    )));
    const manifest = {
        schemaVersion: 2,
        runtimeVersion: "2.0.0",
        coreVersion: "2.0.0",
        pluginMinimumVersion: "2.0.0",
        pluginMaximumVersion: "2.9.9",
        signingKeyId: "release-2026",
        buildCommit: "a".repeat(40),
        createdAt: "2026-07-13T00:00:00Z",
        platform: { os: "windows", architecture: manifestArchitecture, minimumWindowsBuild: 19045 },
        protocol: { minimum: "1.0", maximum: "1.1", schemaHash: `sha256:${"b".repeat(64)}` },
        stateSchemaVersion: 1,
        toolAbiVersion: "1",
        archive: { fileName: "offeragent-runtime.zip", contentDigest, maximumExpandedBytes: 1024 * 1024 },
        bootstrap: {
            path: "offeragent-bootstrap.exe",
            byteLength: helper.length,
            sha256: digest(helper),
            authenticode: true,
            dependencies: [],
        },
        files,
        capabilities: ["offline", "safe_update"],
        privilegeEnvelope: PRIVILEGE_ENVELOPE,
    };
    const manifestBytes = canonical(manifest);
    const { privateKey, publicKey } = generateKeyPairSync("ed25519");
    const signature = Buffer.from(`${base64url(sign(null, manifestBytes, privateKey))}\n`, "ascii");
    const publicDer = publicKey.export({ type: "spki", format: "der" });
    writeFileSync(path.join(platformRoot, "runtime-manifest.json"), manifestBytes);
    writeFileSync(path.join(platformRoot, "runtime-manifest.sig"), signature);
    writeFileSync(path.join(platformRoot, "offeragent-bootstrap.exe"), helper);
    writeFileSync(path.join(platformRoot, "offeragent-runtime.zip"), "zip");
    return {
        plugin,
        root,
        platformRoot,
        manifest,
        manifestBytes,
        privateKey,
        publicKey: base64url(publicDer.subarray(-32)),
        cleanup: () => {
            if (previousLocalAppData === undefined) delete process.env.LOCALAPPDATA;
            else process.env.LOCALAPPDATA = previousLocalAppData;
            rmSync(plugin, { recursive: true, force: true });
        },
    };
}

function fakeBootstrap(bundle, invocations) {
    return (executable, args, options) => {
        const child = new EventEmitter();
        const stderr = new PassThrough();
        const request = new PassThrough();
        const result = new PassThrough();
        child.stdio = [null, null, stderr, request, result];
        child.kill = () => {};
        const invocation = { executable, args, options, request: null };
        invocations.push(invocation);
        const chunks = [];
        request.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
        request.on("end", () => {
            const install = JSON.parse(Buffer.concat(chunks).toString("utf8"));
            invocation.request = install;
            assert.equal(install.bundleRoot, bundle.platformRoot);
            assert.equal(args.includes(bundle.platformRoot), false);
            const manifestHash = digest(bundle.manifestBytes);
            result.write(canonical({ phase: "extracting_to_staging", type: "progress" }));
            result.write(canonical({ phase: "verifying_each_file", type: "progress" }));
            result.write(canonical({ phase: "atomic_activate", type: "progress" }));
            result.write(canonical({ phase: "runtime_self_test", type: "progress" }));
            result.write(canonical({
                bootstrapAuthenticode: true,
                hostExecutable: path.join(
                    process.env.LOCALAPPDATA, "OfferAgent", "runtime", bundle.manifest.runtimeVersion,
                    "offeragent-host.exe",
                ),
                manifestHash,
                protocolMaximum: "1.1",
                protocolMinimum: "1.0",
                privilegeFingerprint: bundle.manifest.privilegeEnvelope.fingerprint,
                runtimeVersion: bundle.manifest.runtimeVersion,
                schemaHash: `sha256:${"b".repeat(64)}`,
                status: "ready",
                type: "result",
            }));
            result.end();
            setImmediate(() => child.emit("exit", 0));
        });
        return child;
    };
}

function installCurrent(bundle, catalogPayload, installed = null) {
    const current = installed ?? {
        manifest: bundle.manifest,
        manifestBytes: bundle.manifestBytes,
        signature: readFileSync(path.join(bundle.platformRoot, "runtime-manifest.sig")),
    };
    const runtimeRoot = path.join(process.env.LOCALAPPDATA, "OfferAgent", "runtime");
    const currentRoot = path.join(runtimeRoot, current.manifest.runtimeVersion);
    mkdirSync(currentRoot, { recursive: true });
    writeFileSync(path.join(currentRoot, "runtime-manifest.json"), current.manifestBytes);
    writeFileSync(path.join(currentRoot, "runtime-manifest.sig"), current.signature);
    writeFileSync(path.join(currentRoot, "process-catalog.v1.json"), catalogPayload);
    writeFileSync(path.join(runtimeRoot, "current.json"), canonical({
        activatedAt: "2026-07-13T00:00:00.000Z",
        currentVersion: current.manifest.runtimeVersion,
        generation: 1,
        manifestHash: digest(current.manifestBytes),
        previousVersion: null,
        privilegeApprovalJournal: [],
        rollbackSnapshot: null,
        stateSchemaVersion: current.manifest.stateSchemaVersion,
    }));
}

function expandedRelease(bundle, productionCatalog, runtimeVersion) {
    const catalogDocument = JSON.parse(productionCatalog.toString("utf8"));
    catalogDocument.environmentProfiles[0].allowedNames = ["OFFERAGENT_SAFE"];
    const catalog = canonical(catalogDocument);
    assert.equal(digest(catalog), "sha256:9085dab6573d8dccc6f7bca20c652b4c896998f43358dd5d98b62aa014cb65a9");
    const manifest = JSON.parse(JSON.stringify(bundle.manifest));
    manifest.runtimeVersion = runtimeVersion;
    manifest.coreVersion = runtimeVersion;
    const catalogRecord = manifest.files.find((item) => item.path === "process-catalog.v1.json");
    catalogRecord.byteLength = catalog.length;
    catalogRecord.sha256 = digest(catalog);
    manifest.archive.contentDigest = digest(Buffer.from(JSON.stringify(
        manifest.files.map(({ path: filePath, byteLength, sha256 }) => ({ byteLength, path: filePath, sha256 })),
    )));
    const envelope = manifest.privilegeEnvelope;
    envelope.processCatalogSha256 = digest(catalog);
    envelope.environmentProfiles[0].allowedNames = ["OFFERAGENT_SAFE"];
    const profileFingerprints = {
        "hook:hook-continue": "sha256:527710fbeb1dd2de179a51147e52070c042b89e2668444a9e8ac6b41453f8427",
        "shell:runtime-info": "sha256:1cf5be0a7803656bd2183a6d1b2d29c951fd7d4c11c93a5769463f97a3942f59",
    };
    for (const profile of envelope.profilePrivileges) {
        profile.allowedPlainEnvironmentNames = ["OFFERAGENT_SAFE"];
        profile.privilegeFingerprint = profileFingerprints[`${profile.kind}:${profile.profileId}`];
    }
    envelope.fingerprint = "sha256:0f5534c341898d3d25afc8e286e11713677191ef1fc8521d175b123ea103d18f";
    const manifestBytes = canonical(manifest);
    const signature = Buffer.from(`${base64url(sign(null, manifestBytes, bundle.privateKey))}\n`, "ascii");
    return { catalog, manifest, manifestBytes, signature };
}

test("embedded installer verifies Ed25519 and invokes only the signed helper over fd3/fd4", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const invocations = [];
    const phases = [];
    let approvalRequest = null;
    try {
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            ownerId: "workspace:ws_12345678-1234-1234-1234-123456789abc",
            legacyOwnerId: "obsidian-4321",
            approvePrivilegeExpansion: async (request) => { approvalRequest = request; return true; },
            spawnProcess: fakeBootstrap(bundle, invocations),
        });
        const runtime = await installer.ensureReady(new AbortController().signal, (phase) => phases.push(phase));

        assert.equal(runtime.version, "2.0.0");
        assert.equal(runtime.hostExecutable.endsWith("offeragent-host.exe"), true);
        assert.equal(runtime.hostDiscoveryTimeoutMs, 10_000);
        assert.deepEqual(invocations[0].args, ["install", "--request-fd", "3", "--result-fd", "4"]);
        assert.equal(invocations[0].options.windowsHide, true);
        assert.equal(invocations[0].options.stdio.length, 5);
        assert.equal(invocations[0].request.ownerId, "workspace:ws_12345678-1234-1234-1234-123456789abc");
        assert.equal(invocations[0].request.legacyOwnerId, "obsidian-4321");
        assert.equal(invocations[0].request.schemaVersion, 3);
        assert.equal(invocations[0].request.vaultRoot, bundle.plugin);
        assert.equal(invocations[0].request.privilegeApproval.confirmation,
            "我确认授予 OfferAgent Runtime 上述本地权限");
        assert.equal(invocations[0].request.privilegeApproval.newPrivilegeFingerprint,
            PRIVILEGE_ENVELOPE.fingerprint);
        assert.equal(invocations[0].request.privilegeApproval.diffHash,
            "sha256:65c93f893c9b63b7c7206e7e855127d6b6517740ed58f3321f870c1d03e9387c");
        assert.equal(approvalRequest.currentRuntimeVersion, null);
        assert.equal(approvalRequest.summary.length > 0 && approvalRequest.summary.length <= 12, true);
        assert.equal(approvalRequest.summary.every((line) => line.length <= 180), true);
        assert.deepEqual(phases, [
            "not_installed", "locating_embedded_bundle", "verifying_manifest_and_signature",
            "extracting_to_staging", "verifying_each_file", "atomic_activate", "runtime_self_test",
            "ready",
        ]);
    } finally {
        bundle.cleanup();
    }
});

test("Node architecture maps only to the matching embedded x64 or ARM64 payload", () => {
    const {
        embeddedPlatformDirectoryForNodeArch,
        runtimeArchitectureForNodeArch,
    } = loadModule();

    assert.equal(runtimeArchitectureForNodeArch("x64"), "x64");
    assert.equal(runtimeArchitectureForNodeArch("arm64"), "arm64");
    assert.equal(embeddedPlatformDirectoryForNodeArch("x64"), "windows-x64");
    assert.equal(embeddedPlatformDirectoryForNodeArch("arm64"), "windows-arm64");
    for (const unsupported of ["ia32", "x86", "aarch64", "unknown", ""]) {
        assert.throws(() => runtimeArchitectureForNodeArch(unsupported), /x64 or arm64/i);
    }
});

test("signed manifest architecture cannot differ from the current Node architecture", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle({ manifestArchitecture: "arm64", bootstrapMachine: 0xaa64 });
    let spawned = false;
    try {
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /verification|platform/i,
        );
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("signed bootstrap PE machine must match the signed Runtime architecture", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle({ bootstrapMachine: 0x014c });
    let spawned = false;
    try {
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /verification|architecture/i,
        );
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("same signed privilege envelope is silent after current pointer, signature, and catalog revalidation", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const invocations = [];
    const catalog = readFileSync(path.join(
        __dirname, "../../../../packages/offeragent-harness/packaging/process-catalog.v1.json",
    ));
    try {
        installCurrent(bundle, catalog);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async () => { throw new Error("same privileges must be silent"); },
            spawnProcess: fakeBootstrap(bundle, invocations),
        });
        await installer.ensureReady(new AbortController().signal, () => {});
        assert.equal(invocations[0].request.privilegeApproval, null);
    } finally {
        bundle.cleanup();
    }
});

test("a Python-golden environment privilege narrowing updates silently", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const invocations = [];
    const productionCatalog = readFileSync(path.join(
        __dirname, "../../../../packages/offeragent-harness/packaging/process-catalog.v1.json",
    ));
    try {
        const current = expandedRelease(bundle, productionCatalog, "1.9.0");
        installCurrent(bundle, current.catalog, current);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async () => { throw new Error("narrowing must be silent"); },
            spawnProcess: fakeBootstrap(bundle, invocations),
        });
        await installer.ensureReady(new AbortController().signal, () => {});
        assert.equal(invocations[0].request.privilegeApproval, null);
    } finally {
        bundle.cleanup();
    }
});

test("a Python-golden environment privilege expansion requires an exact bound receipt", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const invocations = [];
    const productionCatalog = readFileSync(path.join(
        __dirname, "../../../../packages/offeragent-harness/packaging/process-catalog.v1.json",
    ));
    let approvalRequest = null;
    try {
        installCurrent(bundle, productionCatalog);
        const oldManifestHash = digest(bundle.manifestBytes);
        const candidate = expandedRelease(bundle, productionCatalog, "2.1.0");
        bundle.manifest = candidate.manifest;
        bundle.manifestBytes = candidate.manifestBytes;
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.json"), candidate.manifestBytes);
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.sig"), candidate.signature);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async (request) => { approvalRequest = request; return true; },
            spawnProcess: fakeBootstrap(bundle, invocations),
        });
        await installer.ensureReady(new AbortController().signal, () => {});
        const receipt = invocations[0].request.privilegeApproval;
        assert.equal(approvalRequest.currentRuntimeVersion, "2.0.0");
        assert.equal(approvalRequest.summary.some((line) => line.includes("OFFERAGENT_SAFE")), true);
        assert.equal(receipt.oldManifestHash, oldManifestHash);
        assert.equal(receipt.oldPrivilegeFingerprint, PRIVILEGE_ENVELOPE.fingerprint);
        assert.equal(receipt.newPrivilegeFingerprint,
            "sha256:0f5534c341898d3d25afc8e286e11713677191ef1fc8521d175b123ea103d18f");
        assert.equal(receipt.diffHash,
            "sha256:cbecff3c8ec789a73bdfa97c83c0f64760fef4bc5ee2b843bbff5f054de4882e");
    } finally {
        bundle.cleanup();
    }
});

test("tampered current catalog is rejected before approval or bootstrap execution", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const catalog = Buffer.from(readFileSync(path.join(
        __dirname, "../../../../packages/offeragent-harness/packaging/process-catalog.v1.json",
    )));
    catalog[0] = 0x5b;
    let approved = false;
    let spawned = false;
    try {
        installCurrent(bundle, catalog);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async () => { approved = true; return true; },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /verification|catalog/i,
        );
        assert.equal(approved, false);
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("first install cannot proceed without the explicit privilege approval callback", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    let spawned = false;
    try {
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /权限|approval/i,
        );
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("privilege approval receives the installer AbortSignal and releases startup on unload", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    const controller = new AbortController();
    let enteredApproval;
    const approvalEntered = new Promise((resolve) => { enteredApproval = resolve; });
    let spawned = false;
    try {
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async (_request, signal) => {
                assert.equal(signal, controller.signal);
                enteredApproval();
                return await new Promise((resolve) => signal.addEventListener("abort", () => resolve(false), {
                    once: true,
                }));
            },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        const startup = installer.ensureReady(controller.signal, () => {});
        await approvalEntered;
        controller.abort();
        await assert.rejects(startup, (error) => error?.name === "AbortError");
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("signed but internally inconsistent privilege fingerprint is rejected", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    let spawned = false;
    try {
        const manifest = JSON.parse(JSON.stringify(bundle.manifest));
        manifest.privilegeEnvelope.fingerprint = `sha256:${"0".repeat(64)}`;
        const bytes = canonical(manifest);
        const signature = Buffer.from(`${base64url(sign(null, bytes, bundle.privateKey))}\n`, "ascii");
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.json"), bytes);
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.sig"), signature);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            approvePrivilegeExpansion: async () => true,
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /verification|fingerprint/i,
        );
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("manifest signature tamper is rejected before any helper executes", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    let spawned = false;
    try {
        const manifestPath = path.join(bundle.platformRoot, "runtime-manifest.json");
        const tampered = readFileSync(manifestPath, "utf8").replace("2.0.0", "2.0.1");
        writeFileSync(manifestPath, tampered);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(() => installer.ensureReady(new AbortController().signal, () => {}), /verification|signature/i);
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("even correctly signed manifest bytes reject duplicate JSON members", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    let spawned = false;
    try {
        const duplicate = Buffer.from(
            bundle.manifestBytes.toString("utf8").replace(/}\n$/, ',"runtimeVersion":"2.0.0"}\n'),
            "utf8",
        );
        const signature = Buffer.from(`${base64url(sign(null, duplicate, bundle.privateKey))}\n`, "ascii");
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.json"), duplicate);
        writeFileSync(path.join(bundle.platformRoot, "runtime-manifest.sig"), signature);
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(
            () => installer.ensureReady(new AbortController().signal, () => {}),
            /verification|manifest/i,
        );
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});

test("bootstrap file hash tamper is rejected before execution", async () => {
    const { EmbeddedRuntimeInstaller } = loadModule();
    const bundle = makeBundle();
    let spawned = false;
    try {
        writeFileSync(path.join(bundle.platformRoot, "offeragent-bootstrap.exe"), Buffer.concat([peX64(), Buffer.from("x")]));
        const installer = new EmbeddedRuntimeInstaller({
            pluginDirectory: bundle.plugin,
            vaultRoot: bundle.plugin,
            pluginVersion: "2.0.0-beta.28",
            protocolVersion: "1.0",
            schemaHash: `sha256:${"b".repeat(64)}`,
            releasePublicKeys: { "release-2026": bundle.publicKey },
            spawnProcess: () => { spawned = true; throw new Error("must not run"); },
        });
        await assert.rejects(() => installer.ensureReady(new AbortController().signal, () => {}), /verification|size/i);
        assert.equal(spawned, false);
    } finally {
        bundle.cleanup();
    }
});
