# Generated by Django 5.1.15 on 2026-06-30 10:55

import uuid

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    run_before = [
        ("admin", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AiModelApi",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("api_key", models.CharField(max_length=4000)),
                ("api_base_url", models.URLField(blank=True, default=None, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="McpServer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("path", models.CharField(max_length=200, unique=True)),
                ("api_key", models.CharField(blank=True, max_length=4000, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessLock",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("index_content", "Index Content"),
                            ("scheduled_job", "Scheduled Job"),
                            ("schedule_leader", "Schedule Leader"),
                            ("apply_migrations", "Apply Migrations"),
                        ],
                        max_length=200,
                        unique=True,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("max_duration_in_seconds", models.IntegerField(default=43200)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WebScraper",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Friendly name. If not set, it will be set to the type of the scraper.",
                        max_length=200,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Firecrawl", "Firecrawl"),
                            ("Olostep", "Olostep"),
                            ("Exa", "Exa"),
                            ("Direct", "Direct"),
                        ],
                        default="Direct",
                        max_length=20,
                    ),
                ),
                (
                    "api_key",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="API key of the web scraper. Only set if scraper service requires an API key. Default is set from env var.",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "api_url",
                    models.URLField(
                        blank=True,
                        default=None,
                        help_text="API URL of the web scraper. Only set if scraper service on non-default URL.",
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Priority of the web scraper. Lower numbers run first.",
                        null=True,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KhojUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "A user with that username already exists."},
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                        verbose_name="username",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                ("email", models.EmailField(blank=True, max_length=254, verbose_name="email address")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("verified_email", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ChatModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("max_prompt_size", models.IntegerField(blank=True, default=None, null=True)),
                ("name", models.CharField(default="gemini-2.5-flash", max_length=200)),
                ("friendly_name", models.CharField(blank=True, default=None, max_length=200, null=True)),
                (
                    "model_type",
                    models.CharField(
                        choices=[("openai", "Openai"), ("anthropic", "Anthropic"), ("google", "Google")],
                        default="google",
                        max_length=200,
                    ),
                ),
                ("vision_enabled", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default=None, null=True)),
                ("strengths", models.TextField(blank=True, default=None, null=True)),
                (
                    "ai_model_api",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.aimodelapi",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Agent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("personality", models.TextField(blank=True, default=None, null=True)),
                ("slug", models.CharField(default="khoj", max_length=200, unique=True)),
                ("chat_model", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="database.chatmodel")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversation_log", models.JSONField(default=dict)),
                ("slug", models.CharField(blank=True, default=None, max_length=200, null=True)),
                ("title", models.CharField(blank=True, default=None, max_length=500, null=True)),
                ("file_filters", models.JSONField(default=list)),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.agent",
                    ),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FileObject",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file_name", models.CharField(blank=True, default=None, max_length=400, null=True)),
                ("raw_text", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("raw", models.TextField()),
                ("compiled", models.TextField()),
                ("heading", models.CharField(blank=True, default=None, max_length=1000, null=True)),
                (
                    "file_source",
                    models.CharField(choices=[("computer", "Computer")], default="computer", max_length=30),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "Pdf"),
                            ("plaintext", "Plaintext"),
                            ("markdown", "Markdown"),
                            ("conversation", "Conversation"),
                        ],
                        default="plaintext",
                        max_length=30,
                    ),
                ),
                ("file_path", models.CharField(blank=True, default=None, max_length=400, null=True)),
                ("file_name", models.CharField(blank=True, default=None, max_length=400, null=True)),
                ("url", models.URLField(blank=True, default=None, max_length=400, null=True)),
                ("hashed_value", models.CharField(max_length=100)),
                ("corpus_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "file_object",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.fileobject",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KhojApiUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=50)),
                ("accessed_at", models.DateTimeField(default=None, null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name="RateLimitRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.CharField(db_index=True, max_length=255)),
                ("slug", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["identifier", "slug", "created_at"], name="database_ra_identif_031adf_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserConversationConfig",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enable_memory", models.BooleanField(default=True)),
                (
                    "setting",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.chatmodel",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserRequests",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.CharField(max_length=200)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ServerChatSettings",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "priority",
                    models.IntegerField(
                        blank=True,
                        default=None,
                        help_text="Priority of the server chat settings. Lower numbers run first.",
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "memory_mode",
                    models.CharField(
                        choices=[
                            ("disabled", "Disabled"),
                            ("enabled_default_off", "Enabled, default off"),
                            ("enabled_default_on", "Enabled, default on"),
                        ],
                        default="enabled_default_on",
                        help_text="Server-level memory feature configuration. Disabled overrides user preference.",
                        max_length=20,
                    ),
                ),
                (
                    "chat_default",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_default",
                        to="database.chatmodel",
                    ),
                ),
                (
                    "web_scraper",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="web_scraper",
                        to="database.webscraper",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
