# Generated by Django 5.1.15 on 2026-07-08 08:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_drop_removed_product_surfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='output_modes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('diagram', 'Diagram')], max_length=200), blank=True, default=list, null=True, size=None),
        ),
    ]
