# Generated by Django 5.1.15 on 2026-07-10 09:52

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("database", "0006_drop_removed_local_demo_surfaces"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaultActionBatch",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("turn_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("applying", "Applying"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                            ("conflict", "Conflict"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                            ("manual_review_required", "Manual Review Required"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("actions", models.JSONField(default=list)),
                ("snapshots", models.JSONField(default=dict)),
                ("previews", models.JSONField(default=list)),
                ("root_fingerprint", models.CharField(max_length=64)),
                ("action_digest", models.CharField(max_length=64)),
                ("rollback_journal", models.JSONField(default=dict)),
                ("result", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                (
                    "conversation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="database.conversation"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "conversation", "status", "created_at"], name="vault_batch_owner_status_idx"
                    ),
                    models.Index(fields=["status", "expires_at"], name="vault_batch_expiry_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("conversation", "turn_id"), name="unique_vault_batch_turn")
                ],
            },
        ),
    ]
