# Generated by Django 5.1.15 on 2026-06-28 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0099_usermemory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchmodelconfig',
            name='bi_encoder',
            field=models.CharField(default='BAAI/bge-small-zh-v1.5', max_length=200),
        ),
        migrations.AlterField(
            model_name='searchmodelconfig',
            name='bi_encoder_confidence_threshold',
            field=models.FloatField(default=0.55),
        ),
        migrations.AlterField(
            model_name='searchmodelconfig',
            name='cross_encoder',
            field=models.CharField(default='BAAI/bge-reranker-v2-m3', max_length=200),
        ),
    ]
