"""Application primitives used by the local Worker Runtime."""

from .approval_manager import ApprovalManager
from .backpressure import BufferedEventSink
from .cancellation import CancellationReason, CancellationScope, RunCancelled
from .harness_service import RecoveryResumeRejected
from .hook_lifecycle import LifecycleHookDenied, WorkerLifecycleHooks
from .hook_service import (
    HookConfigurationError,
    HookExecutionError,
    HookHandlerRegistry,
    HookInvocationConflict,
    HookService,
    HookServiceError,
    StaticHookLayerSource,
)
from .process_lock import (
    MutexWaitResult,
    ProcessAlreadyRunning,
    ProcessLock,
    ProcessLockError,
)
from .process_supervisor import (
    ActiveProcessSnapshot,
    ExecutableTrust,
    ProcessEnvironmentProfile,
    ProcessExecutableProfile,
    ProcessExecutionError,
    ProcessFilesystemAccess,
    ProcessFilesystemCapability,
    ProcessProfileError,
    ProcessSupervisorService,
    ResolvedProcessFilesystemGrant,
)
from .production_hooks import (
    CompactionHookBinding,
    PreparedHookBundle,
    PreparedHookDefinitionEvidence,
    PreparedHookLayerEvidence,
    ProductionHookBundle,
    ProductionHookBundleError,
    ProductionHookBundleFactory,
    RunBoundHookContextFactory,
    RunBoundHookLifecyclePort,
)
from .production_shell import (
    PreparedShellBundle,
    PreparedShellProfileEvidence,
    ProductionShellBundle,
    ProductionShellBundleError,
    ProductionShellBundleFactory,
)
from .recovery import (
    RecoveryAction,
    RecoveryActionKind,
    RecoveryCoordinator,
    RecoveryDisposition,
    RecoveryError,
    RecoveryIssue,
    RecoveryLookup,
    RecoveryPlan,
    RecoveryScanError,
)
from .recovery_apply import RecoveryApplyBlocked, RecoveryApplyResult, RecoveryPlanApplier
from .run_preparation import (
    ContextInputsEnricher,
    PreparedRunContext,
    RunContextProvider,
    RunPreparationLimits,
    RunPreparationRequest,
)
from .session_service import (
    ArtifactLinkResolver,
    SessionActiveEffectfulRun,
    SessionActiveRunUnavailable,
    SessionCreateCommand,
    SessionCreatePreparation,
    SessionCreateResult,
    SessionCreateState,
    SessionDeleteCommand,
    SessionDeleted,
    SessionDeleteResult,
    SessionForkCommand,
    SessionForkReference,
    SessionForkRejected,
    SessionForkResult,
    SessionGetCommand,
    SessionGetResult,
    SessionIdempotencyConflict,
    SessionLifecycleService,
    SessionListCommand,
    SessionListResult,
    SessionNotFound,
    SessionOperationConflict,
    SessionProjectionCorrupt,
    SessionRenameCommand,
    SessionRenameResult,
    SessionRevisionConflict,
)
from .startup import RuntimeStartupBlocked, RuntimeStartupCoordinator, RuntimeStartupReport, StartupFailurePhase
from .subagent_runtime import (
    HarnessChildCancellationFactory,
    HarnessSubagentRunExecutor,
    ProtocolSubagentEventFactory,
)
from .turn_manager import ActiveRun, SessionRunConflict, TurnManager
from .windows_appcontainer import cleanup_workspace_appcontainer
from .windows_process_supervisor import PinnedProcessExecutableVerifier, WindowsSupervisedProcessBackend
from .windows_security import CurrentWindowsIdentity, WindowsSecurityError, current_windows_identity

__all__ = [
    "ActiveProcessSnapshot",
    "ActiveRun",
    "ApprovalManager",
    "ArtifactLinkResolver",
    "BufferedEventSink",
    "CancellationReason",
    "CancellationScope",
    "CompactionHookBinding",
    "ContextInputsEnricher",
    "CurrentWindowsIdentity",
    "ExecutableTrust",
    "HarnessChildCancellationFactory",
    "HarnessSubagentRunExecutor",
    "HookConfigurationError",
    "HookExecutionError",
    "HookHandlerRegistry",
    "HookInvocationConflict",
    "HookService",
    "HookServiceError",
    "LifecycleHookDenied",
    "MutexWaitResult",
    "PinnedProcessExecutableVerifier",
    "PreparedHookBundle",
    "PreparedHookDefinitionEvidence",
    "PreparedHookLayerEvidence",
    "PreparedRunContext",
    "PreparedShellBundle",
    "PreparedShellProfileEvidence",
    "ProcessAlreadyRunning",
    "ProcessEnvironmentProfile",
    "ProcessExecutableProfile",
    "ProcessExecutionError",
    "ProcessFilesystemAccess",
    "ProcessFilesystemCapability",
    "ProcessLock",
    "ProcessLockError",
    "ProcessProfileError",
    "ProcessSupervisorService",
    "ProductionHookBundle",
    "ProductionHookBundleError",
    "ProductionHookBundleFactory",
    "ProductionShellBundle",
    "ProductionShellBundleError",
    "ProductionShellBundleFactory",
    "ProtocolSubagentEventFactory",
    "RecoveryAction",
    "RecoveryActionKind",
    "RecoveryApplyBlocked",
    "RecoveryApplyResult",
    "RecoveryCoordinator",
    "RecoveryDisposition",
    "RecoveryError",
    "RecoveryIssue",
    "RecoveryLookup",
    "RecoveryPlan",
    "RecoveryPlanApplier",
    "RecoveryResumeRejected",
    "RecoveryScanError",
    "ResolvedProcessFilesystemGrant",
    "RunBoundHookContextFactory",
    "RunBoundHookLifecyclePort",
    "RunCancelled",
    "RunContextProvider",
    "RunPreparationLimits",
    "RunPreparationRequest",
    "RuntimeStartupBlocked",
    "RuntimeStartupCoordinator",
    "RuntimeStartupReport",
    "SessionActiveEffectfulRun",
    "SessionActiveRunUnavailable",
    "SessionCreateCommand",
    "SessionCreatePreparation",
    "SessionCreateResult",
    "SessionCreateState",
    "SessionDeleteCommand",
    "SessionDeleteResult",
    "SessionDeleted",
    "SessionForkCommand",
    "SessionForkReference",
    "SessionForkRejected",
    "SessionForkResult",
    "SessionGetCommand",
    "SessionGetResult",
    "SessionIdempotencyConflict",
    "SessionLifecycleService",
    "SessionListCommand",
    "SessionListResult",
    "SessionNotFound",
    "SessionOperationConflict",
    "SessionProjectionCorrupt",
    "SessionRenameCommand",
    "SessionRenameResult",
    "SessionRevisionConflict",
    "SessionRunConflict",
    "StartupFailurePhase",
    "StaticHookLayerSource",
    "TurnManager",
    "WindowsSecurityError",
    "WindowsSupervisedProcessBackend",
    "WorkerLifecycleHooks",
    "cleanup_workspace_appcontainer",
    "current_windows_identity",
]
