import esbuild from "esbuild";
import process from "process";
import path from "path";
import builtins from 'builtin-modules'

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const localDevelopment = (process.argv[2] === 'local-development');
const prod = (process.argv[2] === 'production') || localDevelopment;
const extraArguments = process.argv.slice(3);
const outputArguments = extraArguments.filter((value) => value.startsWith('--outfile='));
const manifestArguments = extraArguments.filter((value) => value.startsWith('--development-manifest-sha256='));
if (outputArguments.length > 1 || manifestArguments.length > 1 || extraArguments.some((value) =>
    !value.startsWith('--outfile=') && !value.startsWith('--development-manifest-sha256='))) {
    throw new Error('unsupported or duplicate build argument');
}
const requestedOutput = outputArguments.length === 1 ? outputArguments[0].slice('--outfile='.length) : 'main.js';
if (!requestedOutput || requestedOutput.includes('\0')) throw new Error('invalid build outfile');
const outfile = path.resolve(requestedOutput);
const developmentManifestSha256 = manifestArguments.length === 1
    ? manifestArguments[0].slice('--development-manifest-sha256='.length)
    : '';
if (localDevelopment && !/^sha256:[0-9a-f]{64}$/.test(developmentManifestSha256)) {
    throw new Error('local development build requires a canonical manifest SHA-256 anchor');
}
if (!localDevelopment && developmentManifestSha256) {
    throw new Error('production build rejects the local development manifest anchor');
}
const installerSelection = localDevelopment ? [{
    name: "offeragent-local-development-installer",
    setup(build) {
        build.onResolve({ filter: /^\.\/runtime\/installer_mode$/ }, () => ({
            path: path.resolve("src/runtime/installer_mode.local_development.ts"),
        }));
    },
}] : [];

esbuild.build({
    banner: {
        js: banner,
    },
    entryPoints: ['src/main.ts'],
    bundle: true,
    external: [
        'obsidian',
        'electron',
        '@codemirror/autocomplete',
        '@codemirror/collab',
        '@codemirror/commands',
        '@codemirror/language',
        '@codemirror/lint',
        '@codemirror/search',
        '@codemirror/state',
        '@codemirror/view',
        '@lezer/common',
        '@lezer/highlight',
        '@lezer/lr',
        'node:fs',
        'node:path',
        'node:util',
        'node:url',
        'node:http',
        'node:https',
        'node:stream',
        'node:zlib',
        'node:buffer',
        'node:net',
        'node:*',
        ...builtins],
    format: 'cjs',
    watch: !prod,
    target: 'es2018',
    logLevel: "info",
    sourcemap: prod ? false : 'inline',
    treeShaking: true,
    plugins: installerSelection,
    define: localDevelopment ? {
        __OFFERAGENT_DEVELOPMENT_MANIFEST_SHA256__: JSON.stringify(developmentManifestSha256),
    } : {},
    outfile,
}).catch(() => process.exit(1));
