/* Generated by scripts/generate-protocol-identity.mjs; do not edit. */
export const PROTOCOL_VERSION = "1.0";
export const PROTOCOL_SCHEMA_VERSION = "1";
export const PROTOCOL_SCHEMA_HASH = "sha256:291affccfe1cf060d1e6ffb6cb954ef02d24389dd2237fc9a6441a5d2efde71d";
