/* Generated by scripts/generate-protocol-identity.mjs; do not edit. */
export const PROTOCOL_VERSION = "1.0";
export const PROTOCOL_SCHEMA_VERSION = "1";
export const PROTOCOL_SCHEMA_HASH = "sha256:80d269d2ccf312c998f3d1eec68ab6340c983b42b2114481c5a8ffe0e885be79";
