/* Generated by scripts/generate-protocol-identity.mjs; do not edit. */
export const PROTOCOL_VERSION = "1.0";
export const PROTOCOL_SCHEMA_VERSION = "1";
export const PROTOCOL_SCHEMA_HASH = "sha256:8632f14d882301d4ef4bb9f779ed4fb1052967fa9834249060c13b617c239f93";
