/* Generated by scripts/generate-protocol-types.mjs; do not edit. */
export const PROTOCOL_TYPES_SCHEMA_HASH = "sha256:8632f14d882301d4ef4bb9f779ed4fb1052967fa9834249060c13b617c239f93";

export type AgentCancelParams = {
  readonly "cascade"?: boolean;
  readonly "reason": string;
  readonly "runId": RunId;
};

export type AgentCancelResult = {
  readonly "accepted": boolean;
  readonly "descendantRunIds"?: ReadonlyArray<RunId>;
  readonly "runId": RunId;
};

export type AgentResultParams = {
  readonly "include"?: ReadonlyArray<"summary" | "findings" | "evidence" | "artifacts" | "proposedActions" | "usage">;
  readonly "runId": RunId;
};

export type AgentResultResult = {
  readonly "result": SubagentResult;
};

export type AgentStatusParams = {
  readonly "runId": RunId;
};

export type AgentStatusResult = {
  readonly "childRunIds"?: ReadonlyArray<RunId>;
  readonly "run": RunSnapshot;
};

export type ApprovalDecision = "deny" | "allow_once" | "allow_run" | "allow_session" | "allow_persistent";

export type ApprovalDescriptor = {
  readonly "approvalId": ApprovalId;
  readonly "diffArtifact"?: ArtifactRef | null;
  readonly "expectedStateHash"?: Sha256Digest | null;
  readonly "expiresAt": Rfc3339DateTime;
  readonly "includeDescendants"?: boolean;
  readonly "runId": RunId;
  readonly "status": ApprovalStatus;
  readonly "toolCall": ToolCallDescriptor;
  readonly "workspaceId": WorkspaceId;
};

export type ApprovalExpiredPayload = {
  readonly "approvalId": ApprovalId;
  readonly "expiredAt": Rfc3339DateTime;
  readonly "reason": string;
  readonly "resolverId": string;
};

export type ApprovalId = string;

export type ApprovalRequiredPayload = {
  readonly "approval": ApprovalDescriptor;
  readonly "diffArtifactIds"?: ReadonlyArray<ArtifactId>;
  readonly "explanation": string;
};

export type ApprovalResolveParams = {
  readonly "approvalId": ApprovalId;
  readonly "comment"?: string | null;
  readonly "decision": ApprovalDecision;
  readonly "expectedArgsHash": Sha256Digest;
  readonly "includeDescendants"?: boolean;
  readonly "scope": ApprovalScope;
};

export type ApprovalResolveResult = {
  readonly "approvalId": ApprovalId;
  readonly "resumed": boolean;
  readonly "runId": RunId;
  readonly "status": "approved" | "denied" | "expired" | "cancelled" | "already_resolved";
};

export type ApprovalResolvedPayload = {
  readonly "approvalId": ApprovalId;
  readonly "decision": ApprovalDecision;
  readonly "includeDescendants"?: boolean;
  readonly "reason"?: string | null;
  readonly "resolvedAt": Rfc3339DateTime;
  readonly "resolvedBy": "user" | "policy" | "system";
  readonly "resolverId": string;
  readonly "scope": ApprovalScope;
  readonly "status": "approved" | "denied" | "cancelled";
};

export type ApprovalScope = "once" | "run" | "session" | "persistent";

export type ApprovalStatus = "pending" | "approved" | "denied" | "expired" | "cancelled";

export type ArtifactContentBlock = {
  readonly "artifact": ArtifactRef;
  readonly "preview"?: string | null;
  readonly "type": "artifact";
};

export type ArtifactCreatedPayload = {
  readonly "artifact": ArtifactRef;
  readonly "ownerId": string;
  readonly "ownerType": "run" | "tool" | "approval" | "subagent" | "index";
};

export type ArtifactEncoding = "utf8" | "base64";

export type ArtifactId = string;

export type ArtifactReadParams = {
  readonly "artifactId": ArtifactId;
  readonly "maxBytes"?: number;
  readonly "offset"?: number;
};

export type ArtifactReadResult = {
  readonly "artifact": ArtifactRef;
  readonly "content": string;
  readonly "encoding": ArtifactEncoding;
  readonly "eof": boolean;
  readonly "nextOffset": number;
  readonly "offset": number;
};

export type ArtifactRef = {
  readonly "artifactId": ArtifactId;
  readonly "contentHash": Sha256Digest;
  readonly "mediaType": string;
  readonly "sensitivity": ArtifactSensitivity;
  readonly "sizeBytes": number;
  readonly "state"?: ArtifactState;
  readonly "title"?: string | null;
};

export type ArtifactSensitivity = "public" | "workspace" | "private" | "secret";

export type ArtifactSourceRef = {
  readonly "artifact": ArtifactRef;
  readonly "label"?: string | null;
  readonly "type": "artifact";
};

export type ArtifactState = "complete" | "partial" | "unverified" | "cancelled" | "failed";

export type AssistantCompletedPayload = {
  readonly "content": ReadonlyArray<ContentBlock>;
  readonly "finishReason": "stop" | "length" | "cancelled" | "interrupted";
};

export type AssistantDeltaPayload = {
  readonly "blockIndex": number;
  readonly "delta": string;
  readonly "offset": number;
};

export type AttachmentAbortParams = {
  readonly "sessionId": SessionId;
  readonly "uploadId": UploadId;
};

export type AttachmentAbortResult = {
  readonly "aborted": boolean;
  readonly "uploadId": UploadId;
};

export type AttachmentBeginParams = {
  readonly "byteLength": number;
  readonly "clientRequestId": RequestId;
  readonly "contentHash": Sha256Digest;
  readonly "fileName": string;
  readonly "mediaType": string;
  readonly "sessionId": SessionId;
};

export type AttachmentBeginResult = {
  readonly "artifactId": ArtifactId;
  readonly "duplicate": boolean;
  readonly "maxChunkBytes": number;
  readonly "nextOffset": number;
  readonly "uploadId": UploadId;
};

export type AttachmentChunkParams = {
  readonly "contentBase64": string;
  readonly "contentHash": Sha256Digest;
  readonly "offset": number;
  readonly "sessionId": SessionId;
  readonly "uploadId": UploadId;
};

export type AttachmentChunkResult = {
  readonly "duplicate": boolean;
  readonly "receivedBytes": number;
  readonly "uploadId": UploadId;
};

export type AttachmentCommitParams = {
  readonly "sessionId": SessionId;
  readonly "uploadId": UploadId;
};

export type AttachmentCommitResult = {
  readonly "artifact": ArtifactRef;
  readonly "duplicate": boolean;
  readonly "uploadId": UploadId;
};

export type AttachmentReadParams = {
  readonly "artifactId": ArtifactId;
  readonly "maxBytes"?: number;
  readonly "offset"?: number;
  readonly "sessionId": SessionId;
};

export type AttachmentReadResult = {
  readonly "artifact": ArtifactRef;
  readonly "contentBase64": string;
  readonly "eof": boolean;
  readonly "nextOffset": number;
  readonly "offset": number;
};

export type BudgetSnapshot = {
  readonly "maxArtifactBytes": number;
  readonly "maxCostMicros"?: number | null;
  readonly "maxInputTokens"?: number | null;
  readonly "maxModelRounds": number;
  readonly "maxOutputTokens"?: number | null;
  readonly "maxParallelReads": number;
  readonly "maxToolCalls": number;
  readonly "maxWallTimeMs": number;
};

export type CapabilityName = "eventReplay" | "multiSession" | "approvals" | "skills" | "shell" | "hooks" | "subagents" | "artifacts" | "loopbackWeb" | "contentBlocks" | "cancellation" | "diagnostics";

export type CapabilitySet = {
  readonly "approvals"?: boolean;
  readonly "artifacts"?: boolean;
  readonly "cancellation"?: boolean;
  readonly "contentBlocks"?: boolean;
  readonly "diagnostics"?: boolean;
  readonly "eventReplay"?: boolean;
  readonly "hooks"?: boolean;
  readonly "loopbackWeb"?: boolean;
  readonly "multiSession"?: boolean;
  readonly "shell"?: boolean;
  readonly "skills"?: boolean;
  readonly "subagents"?: boolean;
};

export type CompactBoundaryId = string;

export type ConfigFieldError = {
  readonly "code": string;
  readonly "message": string;
  readonly "path": string;
};

export type ConfigGetParams = {
  readonly "scope"?: ConfigScope;
  readonly "sessionId"?: SessionId | null;
};

export type ConfigScope = "user" | "workspace" | "session";

export type ConfigSnapshot = {
  readonly "restartPending"?: boolean;
  readonly "revision": number;
  readonly "scope": ConfigScope;
  readonly "values": Readonly<Record<string, JsonValue>>;
};

export type ConfigUpdateParams = {
  readonly "expectedRevision": number;
  readonly "patch": Readonly<Record<string, JsonValue>>;
  readonly "scope"?: ConfigScope;
  readonly "sessionId"?: SessionId | null;
};

export type ConfigUpdateResult = {
  readonly "fieldErrors"?: ReadonlyArray<ConfigFieldError>;
  readonly "snapshot": ConfigSnapshot;
  readonly "status": "applied" | "restart_required" | "rejected";
};

export type ContentBlock = TextContentBlock | FileContentBlock | ImageContentBlock | ArtifactContentBlock | PinnedContextContentBlock;

export type ContentFormat = "plain" | "markdown";

export type ContextCompactedPayload = {
  readonly "boundaryId": CompactBoundaryId;
  readonly "model": string;
  readonly "replacedSequenceEnd": number;
  readonly "replacedSequenceStart": number;
  readonly "summaryArtifact": ArtifactRef;
};

export type DiagnosticProcessSnapshot = {
  readonly "owned": boolean;
  readonly "pid": number;
  readonly "role": "host" | "worker" | "shell" | "parser";
  readonly "state": string;
};

export type DiagnosticsExportParams = {
  readonly "includeRecentErrors"?: boolean;
  readonly "ownerRunId": RunId;
};

export type DiagnosticsExportPreviewParams = {
  readonly "includeRecentErrors"?: boolean;
};

export type DiagnosticsExportPreviewResult = {
  readonly "containsContent": false;
  readonly "containsPaths": false;
  readonly "estimatedBytes": number;
  readonly "files": ReadonlyArray<string>;
  readonly "uploadDestination"?: null;
};

export type DiagnosticsExportResult = {
  readonly "artifact": ArtifactRef;
  readonly "uploaded"?: false;
};

export type DiagnosticsGetParams = {
  readonly "includePaths"?: false;
  readonly "includeRecentErrors"?: boolean;
};

export type DiagnosticsGetResult = {
  readonly "generatedAt": Rfc3339DateTime;
  readonly "metrics"?: ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "processes": ReadonlyArray<DiagnosticProcessSnapshot>;
  readonly "recentErrors"?: ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "runtime": Readonly<Record<string, JsonValue>>;
};

export type DiagnosticsSnapshotParams = {
  readonly "includeRecentErrors"?: boolean;
};

export type DiagnosticsSnapshotResult = {
  readonly "generatedAt": Rfc3339DateTime;
  readonly "metrics"?: ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "processes": ReadonlyArray<DiagnosticProcessSnapshot>;
  readonly "recentErrors"?: ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "runtime": Readonly<Record<string, JsonValue>>;
};

export type ErrorCode = "protocol.invalid_json" | "protocol.invalid_utf8" | "protocol.invalid_request" | "protocol.method_not_found" | "protocol.invalid_params" | "protocol.message_too_large" | "protocol.duplicate_request_id" | "protocol.schema_mismatch" | "protocol.incompatible_version" | "protocol.missing_capability" | "protocol.internal_error" | "runtime.not_ready" | "runtime.shutting_down" | "runtime.interrupted" | "request.cancelled" | "request.deadline_exceeded" | "resource.not_found" | "resource.conflict" | "policy.denied" | "approval.expired" | "tool.failed" | "tool.unknown_outcome" | "provider.unreachable" | "provider.auth_required" | "provider.context_overflow" | "provider.unsupported" | "internal.error";

export type ErrorEnvelope = {
  readonly "cancelled": boolean;
  readonly "code": ErrorCode;
  readonly "details"?: Readonly<Record<string, JsonValue>>;
  readonly "retryAfterMs"?: number | null;
  readonly "retryable": boolean;
  readonly "traceId"?: TraceId | null;
  readonly "userVisibleMessage": string;
};

export type EventEnvelope = {
  readonly "eventId": EventId;
  readonly "parentRunId"?: RunId | null;
  readonly "payload": EventPayload;
  readonly "protocolVersion": ProtocolVersion;
  readonly "rootRunId"?: RunId | null;
  readonly "runId"?: RunId | null;
  readonly "schemaVersion": SchemaVersion;
  readonly "sequence": number;
  readonly "sessionId"?: SessionId | null;
  readonly "timestamp": Rfc3339DateTime;
  readonly "traceId": TraceId;
  readonly "turnId"?: TurnId | null;
  readonly "type": EventType;
  readonly "workspaceId": WorkspaceId;
};

export type EventId = string;

export type EventNotification = {
  readonly "jsonrpc": "2.0";
  readonly "method": "event";
  readonly "params": EventEnvelope;
};

export type EventPayload = TurnStartedPayload | PhaseChangedPayload | ReasoningSummaryPayload | AssistantDeltaPayload | AssistantCompletedPayload | ToolStartedPayload | ToolCompletedPayload | ToolFailedPayload | ApprovalRequiredPayload | ApprovalResolvedPayload | ApprovalExpiredPayload | ReferencesUpdatedPayload | ArtifactCreatedPayload | UsageUpdatedPayload | ContextCompactedPayload | SessionUpdatedPayload | SubagentQueuedPayload | SubagentStartedPayload | SubagentProgressPayload | SubagentMessageReceivedPayload | SubagentWaitingPayload | SubagentResultAvailablePayload | SubagentCompletedPayload | SubagentFailedPayload | SubagentCancelRequestedPayload | SubagentCancelledPayload | SubagentInterruptedPayload | SubagentOrphanedPayload | SubagentRecoveredPayload | TurnCompletedPayload | TurnCancelledPayload | TurnFailedPayload | TurnInterruptedPayload | RuntimeWarningPayload | ModelAttemptPayload | ToolCallsAcceptedPayload | WriteOutcomeRequiredPayload | RunContinuationRequiredPayload | TurnSteeredPayload;

export type EventType = "turn.started" | "phase.changed" | "reasoning.summary" | "assistant.delta" | "assistant.completed" | "tool.started" | "tool.completed" | "tool.failed" | "approval.required" | "approval.resolved" | "approval.expired" | "references.updated" | "artifact.created" | "usage.updated" | "context.compacted" | "session.updated" | "subagent.queued" | "subagent.started" | "subagent.progress" | "subagent.message_received" | "subagent.waiting" | "subagent.result_available" | "subagent.completed" | "subagent.failed" | "subagent.cancel_requested" | "subagent.cancelled" | "subagent.interrupted" | "subagent.orphaned" | "subagent.recovered" | "turn.completed" | "turn.cancelled" | "turn.failed" | "runtime.warning" | "model.attempt" | "tool.calls.accepted" | "write.outcome_required" | "run.continuation_required" | "turn.interrupted" | "turn.steered";

export type EventsReplayParams = {
  readonly "afterSequence"?: number;
  readonly "limit"?: number;
  readonly "runCursors"?: Readonly<Record<string, number>>;
  readonly "runId"?: RunId | null;
  readonly "sessionId"?: SessionId | null;
  readonly "types"?: ReadonlyArray<EventType>;
};

export type EventsReplayResult = {
  readonly "events": ReadonlyArray<EventEnvelope>;
  readonly "hasMore": boolean;
  readonly "lastSequence"?: number | null;
  readonly "runCursors"?: Readonly<Record<string, number>>;
};

export type ExecutableToolCallDescriptor = {
  readonly "agentLineage": ReadonlyArray<RunId>;
  readonly "argsHash": Sha256Digest;
  readonly "arguments": Readonly<Record<string, JsonValue>>;
  readonly "deadline"?: Rfc3339DateTime | null;
  readonly "definitionFingerprint": Sha256Digest;
  readonly "executorLocation": "local" | "plugin" | "subagent";
  readonly "idempotencyKey": string;
  readonly "name": string;
  readonly "reason"?: string | null;
  readonly "resultSensitivity": "public" | "workspace" | "private" | "secret";
  readonly "risk": ToolRisk;
  readonly "runId": RunId;
  readonly "toolCallId": ToolCallId;
  readonly "version": string;
  readonly "workspaceId": WorkspaceId;
};

export type FileContentBlock = {
  readonly "excerpt"?: string | null;
  readonly "file": FileRef;
  readonly "truncated"?: boolean;
  readonly "type": "file";
};

export type FileRef = {
  readonly "blockId"?: string | null;
  readonly "contentHash"?: Sha256Digest | null;
  readonly "heading"?: string | null;
  readonly "lineEnd"?: number | null;
  readonly "lineStart"?: number | null;
  readonly "path": RelativeVaultPath;
  readonly "workspaceId": WorkspaceId;
};

export type Finding = {
  readonly "confidence"?: number | null;
  readonly "evidence"?: ReadonlyArray<SourceRef>;
  readonly "summary": string;
  readonly "title": string;
};

export type Freshness = "fresh" | "stale" | "partial" | "stale_partial" | "unknown";

export type HookCommandInput = {
  readonly "allowedEnvironment"?: ReadonlyArray<string>;
  readonly "arguments"?: ReadonlyArray<string>;
  readonly "artifactOutputLimitBytes"?: number;
  readonly "cwd"?: string;
  readonly "cwdRootId"?: string;
  readonly "environmentProfileId"?: string;
  readonly "executableId": string;
  readonly "executableProfileFingerprint": Sha256Digest;
};

export type HookDefinitionInput = {
  readonly "command"?: HookCommandInput | null;
  readonly "enabled"?: boolean;
  readonly "event": "SessionStart" | "TurnStart" | "BeforeModel" | "AfterModel" | "PreToolUse" | "PostToolUse" | "ApprovalRequired" | "SubagentStart" | "SubagentStop" | "BeforeCompact" | "TurnStop" | "RuntimeShutdown";
  readonly "handlerId"?: string | null;
  readonly "hookId": string;
  readonly "implementation": "builtin" | "command";
  readonly "outputLimitBytes"?: number;
  readonly "priority"?: number;
  readonly "timeoutMs"?: number;
};

export type HookDefinitionSnapshot = {
  readonly "command"?: HookCommandInput | null;
  readonly "definitionHash": Sha256Digest;
  readonly "enabled"?: boolean;
  readonly "event": "SessionStart" | "TurnStart" | "BeforeModel" | "AfterModel" | "PreToolUse" | "PostToolUse" | "ApprovalRequired" | "SubagentStart" | "SubagentStop" | "BeforeCompact" | "TurnStop" | "RuntimeShutdown";
  readonly "handlerId"?: string | null;
  readonly "hookId": string;
  readonly "implementation": "builtin" | "command";
  readonly "outputLimitBytes"?: number;
  readonly "priority"?: number;
  readonly "timeoutMs"?: number;
};

export type HookLayerInput = {
  readonly "hooks"?: ReadonlyArray<HookDefinitionInput>;
  readonly "ownerId": string;
  readonly "revision": number;
  readonly "scope": "user" | "workspace" | "session";
};

export type HookLayerSnapshot = {
  readonly "commandConfirmations"?: Readonly<Record<string, Sha256Digest>>;
  readonly "contentHash": Sha256Digest;
  readonly "deniedEvents"?: ReadonlyArray<string>;
  readonly "deniedHookIds"?: ReadonlyArray<string>;
  readonly "hooks"?: ReadonlyArray<HookDefinitionSnapshot>;
  readonly "ownerId": string;
  readonly "recordRevision": number;
  readonly "revision": number;
  readonly "scope": "managed" | "user" | "workspace" | "session";
  readonly "trust": "signed" | "confirmed" | "confirmation_required" | "workspace_trust";
};

export type HooksConfirmLayerParams = {
  readonly "clientRequestId": RequestId;
  readonly "contentHash": Sha256Digest;
  readonly "expectedRevision": number;
  readonly "ownerId": string;
  readonly "scope": "user" | "session";
};

export type HooksConfirmWorkspaceCommandParams = {
  readonly "clientRequestId": RequestId;
  readonly "definitionHash": Sha256Digest;
  readonly "expectedRevision": number;
  readonly "hookId": string;
  readonly "ownerId": WorkspaceId;
};

export type HooksInstallParams = {
  readonly "clientRequestId": RequestId;
  readonly "expectedRevision": number;
  readonly "layer": HookLayerInput;
};

export type HooksListParams = Readonly<Record<string, never>>;

export type HooksListResult = {
  readonly "builtinHandlerIds"?: ReadonlyArray<string>;
  readonly "layers"?: ReadonlyArray<HookLayerSnapshot>;
  readonly "profileId": string;
  readonly "revision": number;
  readonly "snapshotHash": Sha256Digest;
  readonly "workspaceId": WorkspaceId;
};

export type HooksMutationResult = {
  readonly "catalogRevision": number;
  readonly "clientRequestId": RequestId;
  readonly "layer": HookLayerSnapshot;
  readonly "snapshotHash": Sha256Digest;
};

export type ImageContentBlock = {
  readonly "altText"?: string | null;
  readonly "artifact": ArtifactRef;
  readonly "type": "image";
};

export type InitializeParams = {
  readonly "capabilities": CapabilitySet;
  readonly "clientVersion": SemanticVersion;
  readonly "protocolVersion": ProtocolVersion;
  readonly "requiredCapabilities"?: ReadonlyArray<CapabilityName>;
  readonly "schemaHash"?: Sha256Digest | null;
  readonly "supportedProtocolRange"?: ProtocolRange | null;
  readonly "workspaceId": WorkspaceId;
};

export type InitializeResult = {
  readonly "buildCommit": string;
  readonly "capabilities": CapabilitySet;
  readonly "coreVersion": SemanticVersion;
  readonly "parentPid": number;
  readonly "protocolVersion": ProtocolVersion;
  readonly "runtimeArch": RuntimeArch;
  readonly "runtimeVersion": SemanticVersion;
  readonly "schemaHash": Sha256Digest;
  readonly "supportedProtocolRange": ProtocolRange;
  readonly "transport": TransportKind;
  readonly "workerPid": number;
  readonly "workspaceId": WorkspaceId;
  readonly "workspaceInstanceId": WorkspaceInstanceId;
};

export type JsonRpcError = {
  readonly "code": JsonRpcErrorCode;
  readonly "data": ErrorEnvelope;
  readonly "message": string;
};

export type JsonRpcErrorCode = -32700 | -32600 | -32601 | -32602 | -32603 | -32000;

export type JsonRpcErrorResponse = {
  readonly "error": JsonRpcError;
  readonly "id": RpcResponseId;
  readonly "jsonrpc": "2.0";
};

export type JsonRpcNotification = {
  readonly "jsonrpc": "2.0";
  readonly "method": string;
  readonly "params"?: Readonly<Record<string, JsonValue>>;
};

export type JsonRpcRequest = {
  readonly "id": RpcId;
  readonly "jsonrpc": "2.0";
  readonly "method": string;
  readonly "params"?: Readonly<Record<string, JsonValue>>;
};

export type JsonRpcSuccessResponse = {
  readonly "id": RpcResponseId;
  readonly "jsonrpc": "2.0";
  readonly "result": JsonValue;
};

export type JsonValue = unknown;

export type MessageId = string;

export type ModelAttemptPayload = {
  readonly "errorCode"?: string | null;
  readonly "omittedContextIds"?: ReadonlyArray<string>;
  readonly "outcome": "succeeded" | "invalid" | "failed";
  readonly "projection"?: "normal" | "overflow_references" | null;
  readonly "projectionHash"?: Sha256Digest | null;
  readonly "repairIndex": number;
  readonly "requestId"?: string | null;
  readonly "retryOfRequestId"?: string | null;
  readonly "usage"?: ModelAttemptUsage | null;
  readonly "violations"?: ReadonlyArray<string>;
};

export type ModelAttemptUsage = {
  readonly "cachedInputTokens"?: number;
  readonly "cost"?: string | null;
  readonly "currency"?: string | null;
  readonly "inputTokens": number;
  readonly "outputTokens": number;
  readonly "reasoningTokens"?: number;
};

export type ModelDescriptor = {
  readonly "available": boolean;
  readonly "displayName": string;
  readonly "local": boolean;
  readonly "maxContextTokens"?: number | null;
  readonly "model": string;
  readonly "provider": string;
  readonly "supportsStreaming": boolean;
  readonly "supportsStructuredOutput": boolean;
  readonly "visionStatus"?: "supported" | "unsupported" | "unverified";
};

export type ModelsHealthParams = {
  readonly "capability"?: "text" | "vision";
  readonly "clientRequestId": RequestId;
  readonly "deadline"?: Rfc3339DateTime | null;
  readonly "model"?: string | null;
  readonly "provider": string;
};

export type ModelsHealthResult = {
  readonly "capability"?: "text" | "vision";
  readonly "checkedAt": Rfc3339DateTime;
  readonly "error"?: ErrorEnvelope | null;
  readonly "latencyMs"?: number | null;
  readonly "model"?: string | null;
  readonly "provider": string;
  readonly "status": "healthy" | "degraded" | "unreachable" | "auth_required" | "unsupported";
};

export type ModelsListParams = {
  readonly "includeUnavailable"?: boolean;
  readonly "provider"?: string | null;
};

export type ModelsListResult = {
  readonly "configRevision": number;
  readonly "models": ReadonlyArray<ModelDescriptor>;
};

export type NonEmptyText = string;

export type PermissionMode = "read-only" | "normal" | "trusted-workspace" | "plan" | "bypass";

export type PersistedSideEffectFact = {
  readonly "afterState"?: JsonValue | null;
  readonly "beforeState"?: JsonValue | null;
  readonly "kind": string;
  readonly "metadata"?: Readonly<Record<string, JsonValue>>;
  readonly "resourceId": string;
  readonly "state": string;
};

export type PersistedToolCall = {
  readonly "argsHash": string;
  readonly "arguments": Readonly<Record<string, JsonValue>>;
  readonly "deadline"?: Rfc3339DateTime | null;
  readonly "definitionFingerprint": string;
  readonly "idempotencyKey": string;
  readonly "lineage": PersistedToolCallLineage;
  readonly "name": string;
  readonly "resultSensitivity"?: "public" | "workspace" | "private" | "secret" | null;
  readonly "toolCallId": ToolCallId;
  readonly "version": string;
};

export type PersistedToolCallLineage = {
  readonly "agentName": string;
  readonly "ancestorRunIds"?: ReadonlyArray<RunId>;
  readonly "depth": number;
  readonly "parentRunId"?: RunId | null;
  readonly "rootRunId": RunId;
  readonly "runId": RunId;
};

export type PhaseChangedPayload = {
  readonly "phase": RunPhase;
  readonly "previousPhase"?: RunPhase | null;
  readonly "reason"?: string | null;
};

export type PinnedContextContentBlock = {
  readonly "references": ReadonlyArray<PinnedContextReference>;
  readonly "type": "pinnedContext";
};

export type PinnedContextReference = PinnedDocumentContextReference | PinnedSelectionContextReference;

export type PinnedDocumentContextReference = {
  readonly "kind": "document";
  readonly "path": RelativeVaultPath;
};

export type PinnedSelectionContextReference = {
  readonly "kind": "selection";
  readonly "lineEnd": number;
  readonly "lineStart": number;
  readonly "path": RelativeVaultPath;
};

export type PluginToolCompleteParams = {
  readonly "argsHash": Sha256Digest;
  readonly "definitionFingerprint": Sha256Digest;
  readonly "idempotencyKey": string;
  readonly "result": ToolResultDescriptor;
  readonly "runId": RunId;
  readonly "workspaceId": WorkspaceId;
};

export type PluginToolCompleteResult = {
  readonly "accepted"?: true;
  readonly "replayed": boolean;
};

export type ProcessEnvironmentProbeSnapshot = {
  readonly "allowedNames"?: ReadonlyArray<string>;
  readonly "allowedSecretNames"?: ReadonlyArray<string>;
  readonly "profileId": string;
};

export type ProcessEnvironmentRegistrationInput = {
  readonly "allowedNames"?: ReadonlyArray<string>;
  readonly "allowedSecretNames"?: ReadonlyArray<string>;
  readonly "expectedContentHash"?: Sha256Digest | null;
  readonly "expectedRevision"?: number;
  readonly "profileId": string;
};

export type ProcessEnvironmentRegistrationSnapshot = {
  readonly "allowedNames"?: ReadonlyArray<string>;
  readonly "allowedSecretNames"?: ReadonlyArray<string>;
  readonly "available": boolean;
  readonly "contentHash": Sha256Digest;
  readonly "profileId": string;
  readonly "revision": number;
  readonly "unavailableReason"?: "configuration_drift" | null;
};

export type ProcessExecutableProbeSnapshot = {
  readonly "allowNetwork"?: false;
  readonly "allowedCwdRootIds": ReadonlyArray<string>;
  readonly "allowedStdinModes": ReadonlyArray<"closed" | "fixed_payload" | "duplex">;
  readonly "appcontainerFilesystem": ReadonlyArray<ProcessFilesystemRegistrationInput>;
  readonly "authenticodeVerified": boolean;
  readonly "canonicalPath": string;
  readonly "environmentProfileIds": ReadonlyArray<string>;
  readonly "executableId": string;
  readonly "fileDevice": string;
  readonly "fileIndex": string;
  readonly "fileSha256": Sha256Digest;
  readonly "fileSize": number;
  readonly "fixedArguments"?: ReadonlyArray<string>;
  readonly "fixedRoot": string;
  readonly "maximumVariableArguments": number;
  readonly "minimumVariableArguments": number;
  readonly "profileFingerprint": Sha256Digest;
  readonly "trust": "fixed_hash" | "os_authenticode";
  readonly "variableArgumentPattern": string;
};

export type ProcessExecutableRegistrationInput = {
  readonly "allowNetwork"?: false;
  readonly "allowedCwdRootIds": ReadonlyArray<string>;
  readonly "allowedStdinModes": ReadonlyArray<"closed" | "fixed_payload" | "duplex">;
  readonly "appcontainerFilesystem": ReadonlyArray<ProcessFilesystemRegistrationInput>;
  readonly "environmentProfileIds": ReadonlyArray<string>;
  readonly "executableId": string;
  readonly "executablePath": string;
  readonly "expectedContentHash"?: Sha256Digest | null;
  readonly "expectedRevision"?: number;
  readonly "fixedArguments"?: ReadonlyArray<string>;
  readonly "maximumVariableArguments"?: number;
  readonly "minimumVariableArguments"?: number;
  readonly "variableArgumentPattern"?: string;
};

export type ProcessExecutableRegistrationSnapshot = {
  readonly "allowNetwork"?: false;
  readonly "allowedCwdRootIds": ReadonlyArray<string>;
  readonly "allowedStdinModes": ReadonlyArray<"closed" | "fixed_payload" | "duplex">;
  readonly "appcontainerFilesystem": ReadonlyArray<ProcessFilesystemRegistrationInput>;
  readonly "authenticodeVerified": boolean;
  readonly "available": boolean;
  readonly "canonicalPath": string;
  readonly "contentHash": Sha256Digest;
  readonly "environmentProfileIds": ReadonlyArray<string>;
  readonly "executableId": string;
  readonly "fileDevice": string;
  readonly "fileIndex": string;
  readonly "fileSha256": Sha256Digest;
  readonly "fileSize": number;
  readonly "fixedArguments"?: ReadonlyArray<string>;
  readonly "fixedRoot": string;
  readonly "maximumVariableArguments": number;
  readonly "minimumVariableArguments": number;
  readonly "profileFingerprint": Sha256Digest;
  readonly "revision": number;
  readonly "trust": "fixed_hash" | "os_authenticode";
  readonly "unavailableReason"?: "file_or_profile_drift" | "configuration_drift" | null;
  readonly "variableArgumentPattern": string;
};

export type ProcessFilesystemRegistrationInput = {
  readonly "access": "read" | "read_write";
  readonly "relativePath": string;
  readonly "rootId": string;
};

export type ProcessRegistrationsConfirmParams = {
  readonly "challengeId": string;
  readonly "clientRequestId": RequestId;
  readonly "expectedCatalogRevision": number;
  readonly "expectedProbeContentHash": Sha256Digest;
};

export type ProcessRegistrationsDeleteParams = {
  readonly "clientRequestId": RequestId;
  readonly "expectedCatalogRevision": number;
  readonly "expectedContentHash": Sha256Digest;
  readonly "expectedRevision": number;
  readonly "kind": "executable" | "environment";
  readonly "registrationId": string;
};

export type ProcessRegistrationsListParams = Readonly<Record<string, never>>;

export type ProcessRegistrationsListResult = {
  readonly "activeCatalogRevision": number;
  readonly "catalogRevision": number;
  readonly "environments"?: ReadonlyArray<ProcessEnvironmentRegistrationSnapshot>;
  readonly "executables"?: ReadonlyArray<ProcessExecutableRegistrationSnapshot>;
  readonly "restartRequired": boolean;
  readonly "snapshotHash": Sha256Digest;
  readonly "workspaceId": WorkspaceId;
};

export type ProcessRegistrationsMutationResult = {
  readonly "catalogRevision": number;
  readonly "clientRequestId": RequestId;
  readonly "deleted": boolean;
  readonly "kind": "executable" | "environment";
  readonly "recordContentHash": Sha256Digest;
  readonly "recordRevision": number;
  readonly "registrationId": string;
  readonly "restartRequired": true;
  readonly "snapshotHash": Sha256Digest;
};

export type ProcessRegistrationsProbeParams = {
  readonly "environment"?: ProcessEnvironmentRegistrationInput | null;
  readonly "executable"?: ProcessExecutableRegistrationInput | null;
};

export type ProcessRegistrationsProbeResult = {
  readonly "challengeId": string;
  readonly "contentHash": Sha256Digest;
  readonly "environment"?: ProcessEnvironmentProbeSnapshot | null;
  readonly "executable"?: ProcessExecutableProbeSnapshot | null;
  readonly "expiresAt": Rfc3339DateTime;
  readonly "kind": "executable" | "environment";
  readonly "registrationId": string;
};

export type ProjectSourceRef = {
  readonly "contentHash": Sha256Digest;
  readonly "freshness"?: Freshness;
  readonly "label"?: string | null;
  readonly "lineEnd"?: number | null;
  readonly "lineStart"?: number | null;
  readonly "modifiedVersion": string;
  readonly "path": RelativeVaultPath;
  readonly "projectId": string;
  readonly "type": "project";
};

export type ProposedAction = {
  readonly "artifactId": ArtifactId;
  readonly "description": string;
  readonly "targetFiles"?: ReadonlyArray<FileRef>;
};

export type ProtocolRange = {
  readonly "maximum": ProtocolVersion;
  readonly "minimum": ProtocolVersion;
};

export type ProtocolVersion = string;

export type ReasoningEffort = "none" | "minimal" | "low" | "medium" | "high" | "max";

export type ReasoningSummaryPayload = {
  readonly "partial"?: boolean;
  readonly "summary": string;
};

export type ReferencesUpdatedPayload = {
  readonly "references": ReadonlyArray<SourceRef>;
  readonly "replace"?: boolean;
};

export type RelativeVaultPath = string;

export type RequestId = string;

export type Rfc3339DateTime = string;

export type RpcCancelNotification = {
  readonly "jsonrpc": "2.0";
  readonly "method": "rpc/cancel";
  readonly "params": RpcCancelParams;
};

export type RpcCancelParams = {
  readonly "requestId": RpcId;
};

export type RpcId = number | RpcStringId;

export type RpcResponseId = RpcId | null;

export type RpcStringId = string;

export type RunConfigSnapshot = {
  readonly "budgets"?: BudgetSnapshot | null;
  readonly "model": string;
  readonly "permissionMode"?: PermissionMode;
  readonly "provider"?: string;
  readonly "reasoningEffort"?: ReasoningEffort;
};

export type RunContinuationRequiredPayload = {
  readonly "blockers": ReadonlyArray<string>;
};

export type RunId = string;

export type RunPhase = "created" | "loading_context" | "selecting_memory" | "planning" | "validating_calls" | "checking_policy" | "awaiting_approval" | "executing_tools" | "recording_results" | "waiting_children" | "responding" | "persisting" | "cancelling" | "terminal";

export type RunSnapshot = {
  readonly "agentName"?: string;
  readonly "completedAt"?: Rfc3339DateTime | null;
  readonly "depth"?: number;
  readonly "error"?: ErrorEnvelope | null;
  readonly "lastSequence"?: number;
  readonly "parentRunId"?: RunId | null;
  readonly "phase": RunPhase;
  readonly "rootRunId": RunId;
  readonly "runId": RunId;
  readonly "sessionId": SessionId;
  readonly "startedAt"?: Rfc3339DateTime | null;
  readonly "status": RunStatus;
  readonly "terminationReason"?: TerminationReason | null;
  readonly "turnId": TurnId;
  readonly "usage": UsageSnapshot;
};

export type RunStatus = "created" | "queued" | "running" | "awaiting_approval" | "waiting_children" | "completed" | "cancel_requested" | "cancelled" | "failed" | "interrupted" | "orphaned";

export type RuntimeArch = "win-x64";

export type RuntimePingParams = {
  readonly "nonce": RequestId;
};

export type RuntimePingResult = {
  readonly "nonce": RequestId;
  readonly "timestamp": Rfc3339DateTime;
  readonly "workerPid": number;
};

export type RuntimeState = "cold" | "starting" | "ready" | "busy" | "idle" | "degraded" | "recovering" | "stopping";

export type RuntimeStatusParams = Readonly<Record<string, never>>;

export type RuntimeStatusResult = {
  readonly "activeRunIds"?: ReadonlyArray<RunId>;
  readonly "coreVersion": SemanticVersion;
  readonly "databaseIdentity": Sha256Digest;
  readonly "parentPid": number;
  readonly "protocolVersion": ProtocolVersion;
  readonly "runtimeVersion": SemanticVersion;
  readonly "schemaHash": Sha256Digest;
  readonly "skills": SkillCatalogStatusSnapshot;
  readonly "state": RuntimeState;
  readonly "warnings"?: ReadonlyArray<ErrorEnvelope>;
  readonly "workerPid": number;
  readonly "workspaceId": WorkspaceId;
  readonly "workspaceInstanceId": WorkspaceInstanceId;
};

export type RuntimeWarningPayload = {
  readonly "code": string;
  readonly "disabledCapabilities"?: ReadonlyArray<CapabilityName>;
  readonly "message": string;
  readonly "recommendedAction"?: string | null;
};

export type SchemaVersion = string;

export type SecretMetadataSnapshot = {
  readonly "createdAt": Rfc3339DateTime;
  readonly "handle": string;
  readonly "kind": "model-provider";
  readonly "providerId": string;
  readonly "rotatedAt": Rfc3339DateTime;
  readonly "version": number;
};

export type SecretsDeleteParams = {
  readonly "expectedVersion": number;
  readonly "handle": string;
};

export type SecretsDeleteResult = {
  readonly "deleted": true;
  readonly "handle": string;
};

export type SecretsListParams = {
  readonly "kind"?: "model-provider" | null;
  readonly "providerId"?: string | null;
};

export type SecretsListResult = {
  readonly "secrets": ReadonlyArray<SecretMetadataSnapshot>;
};

export type SecretsPutParams = {
  readonly "expectedVersion"?: number | null;
  readonly "handle"?: string | null;
  readonly "kind": "model-provider";
  readonly "providerId": string;
  readonly "secret": string;
};

export type SecretsPutResult = {
  readonly "created": boolean;
  readonly "secret": SecretMetadataSnapshot;
};

export type SemanticVersion = string;

export type SessionCompactParams = {
  readonly "force"?: boolean;
  readonly "sessionId": SessionId;
  readonly "throughTurnId"?: TurnId | null;
};

export type SessionCompactResult = {
  readonly "boundaryArtifact"?: ArtifactRef | null;
  readonly "compacted": boolean;
  readonly "replacedTurnCount": number;
  readonly "sessionId": SessionId;
};

export type SessionCreateParams = {
  readonly "clientRequestId": RequestId;
  readonly "title"?: string | null;
};

export type SessionCreateResult = {
  readonly "created": boolean;
  readonly "session": SessionSummary;
};

export type SessionDeleteParams = {
  readonly "hardDelete"?: boolean;
  readonly "sessionId": SessionId;
};

export type SessionDeleteResult = {
  readonly "activeRunsCancelRequested"?: ReadonlyArray<RunId>;
  readonly "deleted": boolean;
  readonly "sessionId": SessionId;
};

export type SessionDetail = {
  readonly "summary": SessionSummary;
  readonly "turns"?: ReadonlyArray<TurnSnapshot>;
};

export type SessionForkParams = {
  readonly "clientRequestId": RequestId;
  readonly "forkRunId"?: RunId | null;
  readonly "forkTurnId": TurnId;
  readonly "sessionId": SessionId;
  readonly "title"?: string | null;
};

export type SessionForkReferencePayload = {
  readonly "artifactLinkIds"?: ReadonlyArray<ArtifactId>;
  readonly "sourceEventSequence": number;
  readonly "sourceRunId": RunId;
  readonly "sourceSessionId": SessionId;
  readonly "sourceTurnId": TurnId;
  readonly "sourceWorkspaceId": WorkspaceId;
};

export type SessionForkResult = {
  readonly "forkTurnId": TurnId;
  readonly "session": SessionSummary;
  readonly "sourceSessionId": SessionId;
};

export type SessionGetParams = {
  readonly "includeTurns"?: boolean;
  readonly "sessionId": SessionId;
};

export type SessionGetResult = {
  readonly "session": SessionDetail;
};

export type SessionId = string;

export type SessionListParams = {
  readonly "cursor"?: string | null;
  readonly "includeDeleted"?: boolean;
  readonly "limit"?: number;
};

export type SessionListResult = {
  readonly "nextCursor"?: string | null;
  readonly "sessions": ReadonlyArray<SessionSummary>;
};

export type SessionRenameParams = {
  readonly "expectedUpdatedAt"?: Rfc3339DateTime | null;
  readonly "sessionId": SessionId;
  readonly "title": string;
};

export type SessionRenameResult = {
  readonly "session": SessionSummary;
};

export type SessionSummary = {
  readonly "activeRunId"?: RunId | null;
  readonly "createdAt": Rfc3339DateTime;
  readonly "deleted"?: boolean;
  readonly "sessionId": SessionId;
  readonly "title": string;
  readonly "turnCount": number;
  readonly "updatedAt": Rfc3339DateTime;
  readonly "workspaceId": WorkspaceId;
};

export type SessionUpdatedPayload = {
  readonly "changedFields": ReadonlyArray<"created" | "title" | "activeRunId" | "turnCount" | "updatedAt" | "deleted" | "compaction" | "forkReference">;
  readonly "forkReference"?: SessionForkReferencePayload | null;
  readonly "session": SessionSummary;
};

export type Sha256Digest = string;

export type ShellConfirmParams = {
  readonly "clientRequestId": RequestId;
  readonly "contentHash": Sha256Digest;
  readonly "expectedRevision": number;
  readonly "profileId": string;
};

export type ShellEnvironmentRegistrationSnapshot = {
  readonly "allowedNames"?: ReadonlyArray<string>;
  readonly "allowedSecretNames"?: ReadonlyArray<string>;
  readonly "profileId": string;
};

export type ShellExecutableRegistrationSnapshot = {
  readonly "allowNetwork": boolean;
  readonly "allowedCwdRootIds": ReadonlyArray<string>;
  readonly "allowedStdinModes": ReadonlyArray<"closed" | "fixed_payload" | "duplex">;
  readonly "environmentProfileIds": ReadonlyArray<string>;
  readonly "executableId": string;
  readonly "fingerprint": Sha256Digest;
  readonly "fixedArguments"?: ReadonlyArray<string>;
  readonly "maximumVariableArguments": number;
  readonly "minimumVariableArguments": number;
  readonly "variableArgumentPattern": string;
};

export type ShellInstallParams = {
  readonly "clientRequestId": RequestId;
  readonly "expectedRevision": number;
  readonly "profile": ShellProfileInput;
};

export type ShellListParams = {
  readonly "includeDisabled"?: boolean;
};

export type ShellListResult = {
  readonly "environments"?: ReadonlyArray<ShellEnvironmentRegistrationSnapshot>;
  readonly "executables"?: ReadonlyArray<ShellExecutableRegistrationSnapshot>;
  readonly "profiles"?: ReadonlyArray<ShellProfileSnapshot>;
  readonly "revision": number;
  readonly "snapshotHash": Sha256Digest;
  readonly "workspaceId": WorkspaceId;
};

export type ShellMutationResult = {
  readonly "catalogRevision": number;
  readonly "clientRequestId": RequestId;
  readonly "profile": ShellProfileSnapshot;
  readonly "snapshotHash": Sha256Digest;
};

export type ShellProfileInput = {
  readonly "allowNetwork"?: boolean;
  readonly "artifactOutputLimitBytes"?: number;
  readonly "concurrencySafe"?: boolean;
  readonly "cwdRootId"?: string;
  readonly "description": string;
  readonly "environmentProfileId"?: string;
  readonly "executableId": string;
  readonly "executableProfileFingerprint": Sha256Digest;
  readonly "fixedArguments"?: ReadonlyArray<string>;
  readonly "idempotent"?: boolean;
  readonly "inlineOutputLimitBytes"?: number;
  readonly "maximumVariableArguments"?: number;
  readonly "minimumVariableArguments"?: number;
  readonly "profileId": string;
  readonly "retryable"?: boolean;
  readonly "risk": "read" | "network" | "write" | "execute" | "destructive" | "external_path" | "secret_access";
  readonly "sideEffectClass": "none" | "read" | "network" | "write" | "execute" | "destructive" | "unknown";
  readonly "timeoutMs"?: number;
  readonly "variableArgumentPattern"?: string;
  readonly "version"?: SemanticVersion;
};

export type ShellProfileSnapshot = {
  readonly "contentHash": Sha256Digest;
  readonly "enabled": boolean;
  readonly "profile": ShellProfileInput;
  readonly "revision": number;
  readonly "source": "signed_builtin" | "user";
  readonly "trust": "signed" | "confirmed" | "confirmation_required";
};

export type ShellSetEnabledParams = {
  readonly "clientRequestId": RequestId;
  readonly "enabled": boolean;
  readonly "expectedRevision": number;
  readonly "profileId": string;
};

export type ShutdownParams = {
  readonly "gracePeriodMs"?: number;
  readonly "reason": "user" | "plugin_disabled" | "upgrade" | "system_shutdown" | "idle_timeout";
};

export type ShutdownResult = {
  readonly "accepted": boolean;
  readonly "activeRunsCancelRequested"?: ReadonlyArray<RunId>;
};

export type SideEffect = {
  readonly "afterHash"?: Sha256Digest | null;
  readonly "beforeHash"?: Sha256Digest | null;
  readonly "confirmed": boolean;
  readonly "kind": "file_created" | "file_modified" | "file_renamed" | "file_trashed" | "process" | "network";
  readonly "resource": string;
};

export type SkillCatalogStatusSnapshot = {
  readonly "diagnostics"?: ReadonlyArray<SkillDiagnosticSnapshot>;
  readonly "discoveredCount": number;
  readonly "enabledCount": number;
  readonly "partial": boolean;
  readonly "revision": number;
  readonly "snapshotHash": Sha256Digest;
};

export type SkillDiagnosticSnapshot = {
  readonly "code": string;
  readonly "message": string;
  readonly "path"?: string | null;
  readonly "rootId"?: string | null;
  readonly "severity": "warning" | "error";
};

export type SkillSnapshot = {
  readonly "allowedTools"?: ReadonlyArray<string>;
  readonly "description": string;
  readonly "layer": "builtin" | "user" | "workspace";
  readonly "metadataHash": Sha256Digest;
  readonly "name": string;
  readonly "packagePath": string;
  readonly "rootId": string;
};

export type SkillsListParams = Readonly<Record<string, never>>;

export type SkillsListResult = {
  readonly "diagnostics"?: ReadonlyArray<SkillDiagnosticSnapshot>;
  readonly "revision": number;
  readonly "skills"?: ReadonlyArray<SkillSnapshot>;
  readonly "snapshotHash": Sha256Digest;
  readonly "workspaceId": WorkspaceId;
};

export type SkillsStatusParams = Readonly<Record<string, never>>;

export type SkillsStatusResult = {
  readonly "status": SkillCatalogStatusSnapshot;
};

export type SourceRef = VaultSourceRef | ArtifactSourceRef | ProjectSourceRef;

export type SubagentCancelRequestedPayload = {
  readonly "cascade": boolean;
  readonly "childRunId": RunId;
  readonly "reason": string;
};

export type SubagentCancelledPayload = {
  readonly "childRunId": RunId;
  readonly "reason": string;
  readonly "usage": UsageSnapshot;
};

export type SubagentCompletedPayload = {
  readonly "result": SubagentResult;
};

export type SubagentFailedPayload = {
  readonly "childRunId": RunId;
  readonly "error": ErrorEnvelope;
  readonly "usage": UsageSnapshot;
};

export type SubagentInterruptedPayload = {
  readonly "childRunId": RunId;
  readonly "error": ErrorEnvelope;
  readonly "safeCheckpointAvailable": boolean;
};

export type SubagentMessageReceivedPayload = {
  readonly "childRunId": RunId;
  readonly "content": ReadonlyArray<ContentBlock>;
  readonly "messageId": MessageId;
  readonly "mode": "append" | "steer";
};

export type SubagentOrphanedPayload = {
  readonly "childRunId": RunId;
  readonly "leaseExpiredAt": Rfc3339DateTime;
};

export type SubagentProgressPayload = {
  readonly "childRunId": RunId;
  readonly "completedUnits"?: number | null;
  readonly "message": string;
  readonly "phase": RunPhase;
  readonly "totalUnits"?: number | null;
};

export type SubagentQueuedPayload = {
  readonly "agentName": string;
  readonly "childRunId": RunId;
  readonly "depth": number;
  readonly "parentRunId": RunId;
  readonly "task": string;
};

export type SubagentRecoveredPayload = {
  readonly "checkpointSequence": number;
  readonly "childRunId": RunId;
  readonly "previousStatus": RunStatus;
};

export type SubagentResult = {
  readonly "artifacts"?: ReadonlyArray<ArtifactRef>;
  readonly "error"?: ErrorEnvelope | null;
  readonly "evidence"?: ReadonlyArray<Readonly<Record<string, JsonValue>>>;
  readonly "findings"?: ReadonlyArray<Finding>;
  readonly "proposedActions"?: ReadonlyArray<ProposedAction>;
  readonly "runId": RunId;
  readonly "status": RunStatus;
  readonly "summary": string;
  readonly "unresolvedQuestions"?: ReadonlyArray<string>;
  readonly "usage": UsageSnapshot;
};

export type SubagentResultAvailablePayload = {
  readonly "childRunId": RunId;
  readonly "resultArtifactId": ArtifactId;
  readonly "summary": string;
};

export type SubagentStartedPayload = {
  readonly "agentName": string;
  readonly "budget": BudgetSnapshot;
  readonly "childRunId": RunId;
  readonly "contextMode": "none" | "summary" | "selected" | "full";
  readonly "parentRunId": RunId;
};

export type SubagentWaitingPayload = {
  readonly "childRunId": RunId;
  readonly "reason": "tool" | "approval" | "children" | "mailbox" | "provider";
  readonly "waitingOnIds"?: ReadonlyArray<string>;
};

export type TerminationReason = "completed" | "cancelled_by_user" | "budget_exhausted" | "model_error" | "tool_error" | "approval_expired" | "runtime_interrupted" | "provider_unreachable";

export type TextContentBlock = {
  readonly "format"?: ContentFormat;
  readonly "references"?: ReadonlyArray<SourceRef>;
  readonly "text": NonEmptyText;
  readonly "type": "text";
};

export type ToolCallDescriptor = {
  readonly "agentLineage": ReadonlyArray<RunId>;
  readonly "argsHash": Sha256Digest;
  readonly "arguments": Readonly<Record<string, JsonValue>>;
  readonly "idempotencyKey": string;
  readonly "name": string;
  readonly "reason"?: string | null;
  readonly "risk": ToolRisk;
  readonly "toolCallId": ToolCallId;
  readonly "version": string;
};

export type ToolCallId = string;

export type ToolCallStatus = "queued" | "running" | "succeeded" | "failed" | "denied" | "cancelled" | "timed_out" | "conflict" | "partial" | "unknown_outcome";

export type ToolCallsAcceptedPayload = {
  readonly "calls": ReadonlyArray<PersistedToolCall>;
};

export type ToolCompletedPayload = {
  readonly "artifactIds"?: ReadonlyArray<ArtifactId>;
  readonly "result": ToolResultDescriptor;
  readonly "sideEffectFacts"?: ReadonlyArray<PersistedSideEffectFact>;
  readonly "sourceReferenceIds"?: ReadonlyArray<string>;
};

export type ToolFailedPayload = {
  readonly "artifactIds"?: ReadonlyArray<ArtifactId>;
  readonly "result": ToolResultDescriptor;
  readonly "sideEffectFacts"?: ReadonlyArray<PersistedSideEffectFact>;
  readonly "sourceReferenceIds"?: ReadonlyArray<string>;
};

export type ToolResultDescriptor = {
  readonly "artifactRefs"?: ReadonlyArray<ArtifactRef>;
  readonly "data"?: Readonly<Record<string, JsonValue>>;
  readonly "error"?: ErrorEnvelope | null;
  readonly "retryable"?: boolean;
  readonly "sideEffects"?: ReadonlyArray<SideEffect>;
  readonly "sourceRefs"?: ReadonlyArray<SourceRef>;
  readonly "status": ToolCallStatus;
  readonly "summary": string;
  readonly "toolCallId": ToolCallId;
};

export type ToolRisk = "read" | "network" | "write" | "execute" | "destructive" | "external_path" | "secret_access";

export type ToolStartedPayload = {
  readonly "attempt"?: number;
  readonly "call": ExecutableToolCallDescriptor;
};

export type TraceId = string;

export type TransportKind = "loopback-http" | "loopback-websocket" | "stdio";

export type TurnCancelParams = {
  readonly "reason": string;
  readonly "runId"?: RunId | null;
  readonly "sessionId": SessionId;
  readonly "turnId": TurnId;
};

export type TurnCancelResult = {
  readonly "accepted": boolean;
  readonly "alreadyTerminal": boolean;
  readonly "runId": RunId;
};

export type TurnCancelledPayload = {
  readonly "code"?: string | null;
  readonly "partialContent"?: ReadonlyArray<ContentBlock>;
  readonly "reason": string;
  readonly "usage": UsageSnapshot;
};

export type TurnCompletedPayload = {
  readonly "assistantContent": ReadonlyArray<ContentBlock>;
  readonly "reason": TerminationReason;
  readonly "usage": UsageSnapshot;
};

export type TurnFailedPayload = {
  readonly "error": ErrorEnvelope;
  readonly "partialContent"?: ReadonlyArray<ContentBlock>;
  readonly "usage": UsageSnapshot;
};

export type TurnGetParams = {
  readonly "sessionId": SessionId;
  readonly "turnId": TurnId;
};

export type TurnGetResult = {
  readonly "turn": TurnSnapshot;
};

export type TurnId = string;

export type TurnInterruptedPayload = {
  readonly "error": ErrorEnvelope;
  readonly "partialContent"?: ReadonlyArray<ContentBlock>;
  readonly "safeCheckpointAvailable": boolean;
  readonly "usage": UsageSnapshot;
};

export type TurnRetryParams = {
  readonly "idempotencyKey": string;
  readonly "runConfig"?: RunConfigSnapshot | null;
  readonly "sessionId": SessionId;
  readonly "sourceRunId": RunId;
  readonly "turnId": TurnId;
};

export type TurnRetryResult = {
  readonly "accepted": boolean;
  readonly "duplicate"?: boolean;
  readonly "runId": RunId;
  readonly "sessionId": SessionId;
  readonly "turnId": TurnId;
};

export type TurnSnapshot = {
  readonly "assistantContent"?: ReadonlyArray<ContentBlock>;
  readonly "createdAt": Rfc3339DateTime;
  readonly "input": ReadonlyArray<ContentBlock>;
  readonly "runs": ReadonlyArray<RunSnapshot>;
  readonly "selectedRunId": RunId;
  readonly "sessionId": SessionId;
  readonly "status": TurnStatus;
  readonly "turnId": TurnId;
  readonly "updatedAt": Rfc3339DateTime;
};

export type TurnStartParams = {
  readonly "deadline"?: Rfc3339DateTime | null;
  readonly "idempotencyKey": string;
  readonly "input": ReadonlyArray<ContentBlock>;
  readonly "pinnedContext"?: ReadonlyArray<PinnedContextReference>;
  readonly "runConfig": RunConfigSnapshot;
  readonly "sessionId": SessionId;
  readonly "turnId": TurnId;
};

export type TurnStartResult = {
  readonly "accepted": boolean;
  readonly "duplicate"?: boolean;
  readonly "runId": RunId;
  readonly "sessionId": SessionId;
  readonly "turnId": TurnId;
};

export type TurnStartedPayload = {
  readonly "attempt"?: number;
  readonly "input": ReadonlyArray<ContentBlock>;
  readonly "runConfig": RunConfigSnapshot;
};

export type TurnStatus = "created" | "running" | "completed" | "cancelled" | "failed" | "interrupted";

export type TurnSteerParams = {
  readonly "input": ReadonlyArray<ContentBlock>;
  readonly "messageId": MessageId;
  readonly "mode"?: "append" | "steer";
  readonly "runId": RunId;
};

export type TurnSteerResult = {
  readonly "accepted": boolean;
  readonly "applyAfterSequence": number;
  readonly "runId": RunId;
};

export type TurnSteeredPayload = {
  readonly "applyAfterSequence": number;
  readonly "input": ReadonlyArray<ContentBlock>;
  readonly "messageId": MessageId;
  readonly "mode": "append" | "steer";
};

export type UploadId = string;

export type UsageSnapshot = {
  readonly "cachedInputTokens"?: number;
  readonly "costMicros"?: number | null;
  readonly "inputTokens": number;
  readonly "modelCalls"?: number;
  readonly "outputTokens": number;
  readonly "reasoningTokens"?: number;
  readonly "toolCalls"?: number;
  readonly "wallTimeMs"?: number;
};

export type UsageUpdatedPayload = {
  readonly "scope": "model_call" | "run" | "turn" | "agent_tree";
  readonly "usage": UsageSnapshot;
};

export type VaultSourceRef = {
  readonly "file": FileRef;
  readonly "freshness"?: Freshness;
  readonly "label"?: string | null;
  readonly "type": "vault";
  readonly "workspaceRevision"?: number | null;
};

export type WebLaunchParams = Readonly<Record<string, never>>;

export type WebLaunchResult = {
  readonly "expiresAt": Rfc3339DateTime;
  readonly "url": string;
  readonly "workerPid": number;
  readonly "workspaceInstanceId": WorkspaceInstanceId;
};

export type WorkspaceId = string;

export type WorkspaceInstanceId = string;

export type WriteOutcomeRequiredPayload = {
  readonly "reasons": ReadonlyArray<string>;
};

export interface ProtocolCommandMap {
  readonly "agent/cancel": {
    readonly "params": AgentCancelParams;
    readonly "result": AgentCancelResult;
    readonly "requiredCapability": "subagents";
  };
  readonly "agent/result": {
    readonly "params": AgentResultParams;
    readonly "result": AgentResultResult;
    readonly "requiredCapability": "subagents";
  };
  readonly "agent/status": {
    readonly "params": AgentStatusParams;
    readonly "result": AgentStatusResult;
    readonly "requiredCapability": "subagents";
  };
  readonly "approval/resolve": {
    readonly "params": ApprovalResolveParams;
    readonly "result": ApprovalResolveResult;
    readonly "requiredCapability": "approvals";
  };
  readonly "artifact/read": {
    readonly "params": ArtifactReadParams;
    readonly "result": ArtifactReadResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "attachments/abort": {
    readonly "params": AttachmentAbortParams;
    readonly "result": AttachmentAbortResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "attachments/begin": {
    readonly "params": AttachmentBeginParams;
    readonly "result": AttachmentBeginResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "attachments/chunk": {
    readonly "params": AttachmentChunkParams;
    readonly "result": AttachmentChunkResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "attachments/commit": {
    readonly "params": AttachmentCommitParams;
    readonly "result": AttachmentCommitResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "attachments/read": {
    readonly "params": AttachmentReadParams;
    readonly "result": AttachmentReadResult;
    readonly "requiredCapability": "artifacts";
  };
  readonly "config/get": {
    readonly "params": ConfigGetParams;
    readonly "result": ConfigSnapshot;
    readonly "requiredCapability": null;
  };
  readonly "config/update": {
    readonly "params": ConfigUpdateParams;
    readonly "result": ConfigUpdateResult;
    readonly "requiredCapability": null;
  };
  readonly "diagnostics/export": {
    readonly "params": DiagnosticsExportParams;
    readonly "result": DiagnosticsExportResult;
    readonly "requiredCapability": "diagnostics";
  };
  readonly "diagnostics/export-preview": {
    readonly "params": DiagnosticsExportPreviewParams;
    readonly "result": DiagnosticsExportPreviewResult;
    readonly "requiredCapability": "diagnostics";
  };
  readonly "diagnostics/get": {
    readonly "params": DiagnosticsGetParams;
    readonly "result": DiagnosticsGetResult;
    readonly "requiredCapability": "diagnostics";
  };
  readonly "diagnostics/snapshot": {
    readonly "params": DiagnosticsSnapshotParams;
    readonly "result": DiagnosticsSnapshotResult;
    readonly "requiredCapability": "diagnostics";
  };
  readonly "events/replay": {
    readonly "params": EventsReplayParams;
    readonly "result": EventsReplayResult;
    readonly "requiredCapability": "eventReplay";
  };
  readonly "hooks/confirm-layer": {
    readonly "params": HooksConfirmLayerParams;
    readonly "result": HooksMutationResult;
    readonly "requiredCapability": "hooks";
  };
  readonly "hooks/confirm-workspace-command": {
    readonly "params": HooksConfirmWorkspaceCommandParams;
    readonly "result": HooksMutationResult;
    readonly "requiredCapability": "hooks";
  };
  readonly "hooks/install": {
    readonly "params": HooksInstallParams;
    readonly "result": HooksMutationResult;
    readonly "requiredCapability": "hooks";
  };
  readonly "hooks/list": {
    readonly "params": HooksListParams;
    readonly "result": HooksListResult;
    readonly "requiredCapability": "hooks";
  };
  readonly "initialize": {
    readonly "params": InitializeParams;
    readonly "result": InitializeResult;
    readonly "requiredCapability": null;
  };
  readonly "models/health": {
    readonly "params": ModelsHealthParams;
    readonly "result": ModelsHealthResult;
    readonly "requiredCapability": null;
  };
  readonly "models/list": {
    readonly "params": ModelsListParams;
    readonly "result": ModelsListResult;
    readonly "requiredCapability": null;
  };
  readonly "plugin-tools/complete": {
    readonly "params": PluginToolCompleteParams;
    readonly "result": PluginToolCompleteResult;
    readonly "requiredCapability": null;
  };
  readonly "process/registrations/confirm": {
    readonly "params": ProcessRegistrationsConfirmParams;
    readonly "result": ProcessRegistrationsMutationResult;
    readonly "requiredCapability": null;
  };
  readonly "process/registrations/delete": {
    readonly "params": ProcessRegistrationsDeleteParams;
    readonly "result": ProcessRegistrationsMutationResult;
    readonly "requiredCapability": null;
  };
  readonly "process/registrations/list": {
    readonly "params": ProcessRegistrationsListParams;
    readonly "result": ProcessRegistrationsListResult;
    readonly "requiredCapability": null;
  };
  readonly "process/registrations/probe": {
    readonly "params": ProcessRegistrationsProbeParams;
    readonly "result": ProcessRegistrationsProbeResult;
    readonly "requiredCapability": null;
  };
  readonly "runtime/ping": {
    readonly "params": RuntimePingParams;
    readonly "result": RuntimePingResult;
    readonly "requiredCapability": null;
  };
  readonly "runtime/status": {
    readonly "params": RuntimeStatusParams;
    readonly "result": RuntimeStatusResult;
    readonly "requiredCapability": null;
  };
  readonly "secrets/delete": {
    readonly "params": SecretsDeleteParams;
    readonly "result": SecretsDeleteResult;
    readonly "requiredCapability": null;
  };
  readonly "secrets/list": {
    readonly "params": SecretsListParams;
    readonly "result": SecretsListResult;
    readonly "requiredCapability": null;
  };
  readonly "secrets/put": {
    readonly "params": SecretsPutParams;
    readonly "result": SecretsPutResult;
    readonly "requiredCapability": null;
  };
  readonly "session/compact": {
    readonly "params": SessionCompactParams;
    readonly "result": SessionCompactResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/create": {
    readonly "params": SessionCreateParams;
    readonly "result": SessionCreateResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/delete": {
    readonly "params": SessionDeleteParams;
    readonly "result": SessionDeleteResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/fork": {
    readonly "params": SessionForkParams;
    readonly "result": SessionForkResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/get": {
    readonly "params": SessionGetParams;
    readonly "result": SessionGetResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/list": {
    readonly "params": SessionListParams;
    readonly "result": SessionListResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "session/rename": {
    readonly "params": SessionRenameParams;
    readonly "result": SessionRenameResult;
    readonly "requiredCapability": "multiSession";
  };
  readonly "shell/confirm": {
    readonly "params": ShellConfirmParams;
    readonly "result": ShellMutationResult;
    readonly "requiredCapability": "shell";
  };
  readonly "shell/install": {
    readonly "params": ShellInstallParams;
    readonly "result": ShellMutationResult;
    readonly "requiredCapability": "shell";
  };
  readonly "shell/list": {
    readonly "params": ShellListParams;
    readonly "result": ShellListResult;
    readonly "requiredCapability": "shell";
  };
  readonly "shell/set-enabled": {
    readonly "params": ShellSetEnabledParams;
    readonly "result": ShellMutationResult;
    readonly "requiredCapability": "shell";
  };
  readonly "shutdown": {
    readonly "params": ShutdownParams;
    readonly "result": ShutdownResult;
    readonly "requiredCapability": null;
  };
  readonly "skills/list": {
    readonly "params": SkillsListParams;
    readonly "result": SkillsListResult;
    readonly "requiredCapability": "skills";
  };
  readonly "skills/status": {
    readonly "params": SkillsStatusParams;
    readonly "result": SkillsStatusResult;
    readonly "requiredCapability": "skills";
  };
  readonly "turn/cancel": {
    readonly "params": TurnCancelParams;
    readonly "result": TurnCancelResult;
    readonly "requiredCapability": "cancellation";
  };
  readonly "turn/get": {
    readonly "params": TurnGetParams;
    readonly "result": TurnGetResult;
    readonly "requiredCapability": null;
  };
  readonly "turn/retry": {
    readonly "params": TurnRetryParams;
    readonly "result": TurnRetryResult;
    readonly "requiredCapability": null;
  };
  readonly "turn/start": {
    readonly "params": TurnStartParams;
    readonly "result": TurnStartResult;
    readonly "requiredCapability": null;
  };
  readonly "turn/steer": {
    readonly "params": TurnSteerParams;
    readonly "result": TurnSteerResult;
    readonly "requiredCapability": null;
  };
  readonly "web/launch": {
    readonly "params": WebLaunchParams;
    readonly "result": WebLaunchResult;
    readonly "requiredCapability": null;
  };
}

export interface ProtocolEventMap {
  readonly "approval.expired": { readonly "payload": ApprovalExpiredPayload; };
  readonly "approval.required": { readonly "payload": ApprovalRequiredPayload; };
  readonly "approval.resolved": { readonly "payload": ApprovalResolvedPayload; };
  readonly "artifact.created": { readonly "payload": ArtifactCreatedPayload; };
  readonly "assistant.completed": { readonly "payload": AssistantCompletedPayload; };
  readonly "assistant.delta": { readonly "payload": AssistantDeltaPayload; };
  readonly "context.compacted": { readonly "payload": ContextCompactedPayload; };
  readonly "model.attempt": { readonly "payload": ModelAttemptPayload; };
  readonly "phase.changed": { readonly "payload": PhaseChangedPayload; };
  readonly "reasoning.summary": { readonly "payload": ReasoningSummaryPayload; };
  readonly "references.updated": { readonly "payload": ReferencesUpdatedPayload; };
  readonly "run.continuation_required": { readonly "payload": RunContinuationRequiredPayload; };
  readonly "runtime.warning": { readonly "payload": RuntimeWarningPayload; };
  readonly "session.updated": { readonly "payload": SessionUpdatedPayload; };
  readonly "subagent.cancel_requested": { readonly "payload": SubagentCancelRequestedPayload; };
  readonly "subagent.cancelled": { readonly "payload": SubagentCancelledPayload; };
  readonly "subagent.completed": { readonly "payload": SubagentCompletedPayload; };
  readonly "subagent.failed": { readonly "payload": SubagentFailedPayload; };
  readonly "subagent.interrupted": { readonly "payload": SubagentInterruptedPayload; };
  readonly "subagent.message_received": { readonly "payload": SubagentMessageReceivedPayload; };
  readonly "subagent.orphaned": { readonly "payload": SubagentOrphanedPayload; };
  readonly "subagent.progress": { readonly "payload": SubagentProgressPayload; };
  readonly "subagent.queued": { readonly "payload": SubagentQueuedPayload; };
  readonly "subagent.recovered": { readonly "payload": SubagentRecoveredPayload; };
  readonly "subagent.result_available": { readonly "payload": SubagentResultAvailablePayload; };
  readonly "subagent.started": { readonly "payload": SubagentStartedPayload; };
  readonly "subagent.waiting": { readonly "payload": SubagentWaitingPayload; };
  readonly "tool.calls.accepted": { readonly "payload": ToolCallsAcceptedPayload; };
  readonly "tool.completed": { readonly "payload": ToolCompletedPayload; };
  readonly "tool.failed": { readonly "payload": ToolFailedPayload; };
  readonly "tool.started": { readonly "payload": ToolStartedPayload; };
  readonly "turn.cancelled": { readonly "payload": TurnCancelledPayload; };
  readonly "turn.completed": { readonly "payload": TurnCompletedPayload; };
  readonly "turn.failed": { readonly "payload": TurnFailedPayload; };
  readonly "turn.interrupted": { readonly "payload": TurnInterruptedPayload; };
  readonly "turn.started": { readonly "payload": TurnStartedPayload; };
  readonly "turn.steered": { readonly "payload": TurnSteeredPayload; };
  readonly "usage.updated": { readonly "payload": UsageUpdatedPayload; };
  readonly "write.outcome_required": { readonly "payload": WriteOutcomeRequiredPayload; };
}

export interface ProtocolEnvelopeMap {
  readonly "error": ErrorEnvelope;
  readonly "errorResponse": JsonRpcErrorResponse;
  readonly "event": EventEnvelope;
  readonly "eventNotification": EventNotification;
  readonly "notification": JsonRpcNotification;
  readonly "request": JsonRpcRequest;
  readonly "rpcCancelNotification": RpcCancelNotification;
  readonly "successResponse": JsonRpcSuccessResponse;
}

export const PROTOCOL_COMMAND_METHODS = Object.freeze(["agent/cancel","agent/result","agent/status","approval/resolve","artifact/read","attachments/abort","attachments/begin","attachments/chunk","attachments/commit","attachments/read","config/get","config/update","diagnostics/export","diagnostics/export-preview","diagnostics/get","diagnostics/snapshot","events/replay","hooks/confirm-layer","hooks/confirm-workspace-command","hooks/install","hooks/list","initialize","models/health","models/list","plugin-tools/complete","process/registrations/confirm","process/registrations/delete","process/registrations/list","process/registrations/probe","runtime/ping","runtime/status","secrets/delete","secrets/list","secrets/put","session/compact","session/create","session/delete","session/fork","session/get","session/list","session/rename","shell/confirm","shell/install","shell/list","shell/set-enabled","shutdown","skills/list","skills/status","turn/cancel","turn/get","turn/retry","turn/start","turn/steer","web/launch"] as const);

export const PROTOCOL_EVENT_TYPES = Object.freeze(["approval.expired","approval.required","approval.resolved","artifact.created","assistant.completed","assistant.delta","context.compacted","model.attempt","phase.changed","reasoning.summary","references.updated","run.continuation_required","runtime.warning","session.updated","subagent.cancel_requested","subagent.cancelled","subagent.completed","subagent.failed","subagent.interrupted","subagent.message_received","subagent.orphaned","subagent.progress","subagent.queued","subagent.recovered","subagent.result_available","subagent.started","subagent.waiting","tool.calls.accepted","tool.completed","tool.failed","tool.started","turn.cancelled","turn.completed","turn.failed","turn.interrupted","turn.started","turn.steered","usage.updated","write.outcome_required"] as const);

export const PROTOCOL_ERROR_CODES = Object.freeze(["protocol.invalid_json","protocol.invalid_utf8","protocol.invalid_request","protocol.method_not_found","protocol.invalid_params","protocol.message_too_large","protocol.duplicate_request_id","protocol.schema_mismatch","protocol.incompatible_version","protocol.missing_capability","protocol.internal_error","runtime.not_ready","runtime.shutting_down","runtime.interrupted","request.cancelled","request.deadline_exceeded","resource.not_found","resource.conflict","policy.denied","approval.expired","tool.failed","tool.unknown_outcome","provider.unreachable","provider.auth_required","provider.context_overflow","provider.unsupported","internal.error"] as const);

export const PROTOCOL_JSON_RPC_ERROR_CODES = Object.freeze([-32700,-32600,-32601,-32602,-32603,-32000] as const);

export const PROTOCOL_RPC_CANCEL_METHOD = "rpc/cancel" as const;

export const PROTOCOL_EVENT_NOTIFICATION_METHOD = "event" as const;

export type ProtocolCommandMethod = keyof ProtocolCommandMap;
export type ProtocolCommandParams<Method extends ProtocolCommandMethod> = ProtocolCommandMap[Method]["params"];
export type ProtocolCommandResult<Method extends ProtocolCommandMethod> = ProtocolCommandMap[Method]["result"];
export type ProtocolEventType = keyof ProtocolEventMap;
export type ProtocolEventPayload<Type extends ProtocolEventType> = ProtocolEventMap[Type]["payload"];
