// Generated by scripts/build_windows_release.py. Public trust roots only.
// Rotation requires a release build whose external Ed25519 private key matches
// the new public key; private key material is never written to this repository.
export const RELEASE_PUBLIC_KEYS: Readonly<Record<string, string>> = Object.freeze({
    "release-2026": "ZdYeBTPHlqxl2LYrwgVPNn3oXjWKy3xPDOy6Wxx9FN8",
});
