"""Model-provider adapters behind the sole ModelGateway port."""

from .codex_subscription import (
    CODEX_CATALOG_CLIENT_VERSION,
    CODEX_SUBSCRIPTION_BASE_URL,
    CODEX_SUBSCRIPTION_MODELS_ENDPOINT,
    CODEX_SUBSCRIPTION_PROVIDER_ID,
    AccountBoundModelCredentialSource,
    CodexCatalogError,
    CodexCatalogHttpAdapter,
    CodexCatalogHttpRequest,
    CodexCatalogHttpResponse,
    CodexCatalogModel,
    CodexCatalogTransportError,
    CodexModelCatalogSnapshot,
    CodexModelServiceTier,
    CodexRunBinding,
    CodexRunBindingError,
    CodexSubscriptionModelModule,
    HttpxCodexCatalogHttpAdapter,
)
from .composition import compose_model_gateway
from .network_audit import ModelNetworkAuditError, ModelNetworkAuditor
from .openai_responses import (
    ModelCredentialLease,
    ModelCredentialSource,
    ModelCredentialSourceError,
    ModelEndpointPolicy,
    ModelProviderConfigurationError,
    ModelProviderProtocolError,
    OpenAIResponsesConfig,
    OpenAIResponsesGateway,
    StaticModelEndpointPolicy,
)

__all__ = [
    "CODEX_CATALOG_CLIENT_VERSION",
    "CODEX_SUBSCRIPTION_BASE_URL",
    "CODEX_SUBSCRIPTION_MODELS_ENDPOINT",
    "CODEX_SUBSCRIPTION_PROVIDER_ID",
    "AccountBoundModelCredentialSource",
    "CodexCatalogError",
    "CodexCatalogHttpAdapter",
    "CodexCatalogHttpRequest",
    "CodexCatalogHttpResponse",
    "CodexCatalogModel",
    "CodexCatalogTransportError",
    "CodexModelCatalogSnapshot",
    "CodexModelServiceTier",
    "CodexRunBinding",
    "CodexRunBindingError",
    "CodexSubscriptionModelModule",
    "HttpxCodexCatalogHttpAdapter",
    "ModelCredentialLease",
    "ModelCredentialSource",
    "ModelCredentialSourceError",
    "ModelEndpointPolicy",
    "ModelNetworkAuditError",
    "ModelNetworkAuditor",
    "ModelProviderConfigurationError",
    "ModelProviderProtocolError",
    "OpenAIResponsesConfig",
    "OpenAIResponsesGateway",
    "StaticModelEndpointPolicy",
    "compose_model_gateway",
]
